/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


export const ListStoreCategoriesResponseItem = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullable(),
  "active": zod.boolean(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})
export const ListStoreCategoriesResponse = zod.array(ListStoreCategoriesResponseItem)


export const GetStoreCategoryParams = zod.object({
  "slug": zod.coerce.string()
})

export const GetStoreCategoryResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullable(),
  "active": zod.boolean(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const listStoreProductsQueryLimitDefault = 24;
export const listStoreProductsQueryLimitMax = 100;

export const listStoreProductsQueryOffsetDefault = 0;
export const listStoreProductsQueryOffsetMin = 0;



export const ListStoreProductsQueryParams = zod.object({
  "category": zod.coerce.string().optional(),
  "limit": zod.coerce.number().int().min(1).max(listStoreProductsQueryLimitMax).default(listStoreProductsQueryLimitDefault),
  "offset": zod.coerce.number().int().min(listStoreProductsQueryOffsetMin).default(listStoreProductsQueryOffsetDefault)
})

export const ListStoreProductsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "categoryId": zod.string().uuid().nullable(),
  "categoryName": zod.string().nullable(),
  "name": zod.string(),
  "slug": zod.string(),
  "productType": zod.enum(['digital', 'ai_tool']),
  "summary": zod.string().nullable(),
  "description": zod.string().nullable(),
  "features": zod.array(zod.string()),
  "requirements": zod.array(zod.string()),
  "imageUrl": zod.string().url().nullable(),
  "whopProductId": zod.string().nullable(),
  "whopProductUrl": zod.string().url().nullable(),
  "deliveryUrl": zod.string().url().nullable(),
  "deliveryInstructions": zod.string().nullable(),
  "status": zod.enum(['draft', 'published', 'archived']),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})
export const ListStoreProductsResponse = zod.array(ListStoreProductsResponseItem)


export const GetStoreProductParams = zod.object({
  "slug": zod.coerce.string()
})

export const GetStoreProductResponse = zod.object({
  "id": zod.string().uuid(),
  "categoryId": zod.string().uuid().nullable(),
  "categoryName": zod.string().nullable(),
  "name": zod.string(),
  "slug": zod.string(),
  "productType": zod.enum(['digital', 'ai_tool']),
  "summary": zod.string().nullable(),
  "description": zod.string().nullable(),
  "features": zod.array(zod.string()),
  "requirements": zod.array(zod.string()),
  "imageUrl": zod.string().url().nullable(),
  "whopProductId": zod.string().nullable(),
  "whopProductUrl": zod.string().url().nullable(),
  "deliveryUrl": zod.string().url().nullable(),
  "deliveryInstructions": zod.string().nullable(),
  "status": zod.enum(['draft', 'published', 'archived']),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const searchStoreProductsQueryQMax = 200;

export const searchStoreProductsQueryLimitDefault = 24;
export const searchStoreProductsQueryLimitMax = 100;



export const SearchStoreProductsQueryParams = zod.object({
  "q": zod.coerce.string().min(1).max(searchStoreProductsQueryQMax),
  "limit": zod.coerce.number().int().min(1).max(searchStoreProductsQueryLimitMax).default(searchStoreProductsQueryLimitDefault)
})

export const SearchStoreProductsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "categoryId": zod.string().uuid().nullable(),
  "categoryName": zod.string().nullable(),
  "name": zod.string(),
  "slug": zod.string(),
  "productType": zod.enum(['digital', 'ai_tool']),
  "summary": zod.string().nullable(),
  "description": zod.string().nullable(),
  "features": zod.array(zod.string()),
  "requirements": zod.array(zod.string()),
  "imageUrl": zod.string().url().nullable(),
  "whopProductId": zod.string().nullable(),
  "whopProductUrl": zod.string().url().nullable(),
  "deliveryUrl": zod.string().url().nullable(),
  "deliveryInstructions": zod.string().nullable(),
  "status": zod.enum(['draft', 'published', 'archived']),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})
export const SearchStoreProductsResponse = zod.array(SearchStoreProductsResponseItem)


export const ListAdminStoreCategoriesResponseItem = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullable(),
  "active": zod.boolean(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})
export const ListAdminStoreCategoriesResponse = zod.array(ListAdminStoreCategoriesResponseItem)


export const createAdminStoreCategoryBodyNameMax = 120;

export const createAdminStoreCategoryBodySlugMax = 160;


export const createAdminStoreCategoryBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)*$');
export const createAdminStoreCategoryBodyDescriptionMax = 2000;

export const createAdminStoreCategoryBodyActiveDefault = false;

export const CreateAdminStoreCategoryBody = zod.object({
  "name": zod.string().min(1).max(createAdminStoreCategoryBodyNameMax),
  "slug": zod.string().max(createAdminStoreCategoryBodySlugMax).regex(createAdminStoreCategoryBodySlugRegExp),
  "description": zod.string().max(createAdminStoreCategoryBodyDescriptionMax).nullish(),
  "active": zod.boolean().default(createAdminStoreCategoryBodyActiveDefault)
})

export const CreateAdminStoreCategoryResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullable(),
  "active": zod.boolean(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const UpdateAdminStoreCategoryParams = zod.object({
  "id": zod.coerce.string().uuid()
})

export const updateAdminStoreCategoryBodyNameMax = 120;

export const updateAdminStoreCategoryBodySlugMax = 160;


export const updateAdminStoreCategoryBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)*$');
export const updateAdminStoreCategoryBodyDescriptionMax = 2000;



export const UpdateAdminStoreCategoryBody = zod.object({
  "name": zod.string().min(1).max(updateAdminStoreCategoryBodyNameMax).optional(),
  "slug": zod.string().max(updateAdminStoreCategoryBodySlugMax).regex(updateAdminStoreCategoryBodySlugRegExp).optional(),
  "description": zod.string().max(updateAdminStoreCategoryBodyDescriptionMax).nullish(),
  "active": zod.boolean().optional()
})

export const UpdateAdminStoreCategoryResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string().nullable(),
  "active": zod.boolean(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const DeleteAdminStoreCategoryParams = zod.object({
  "id": zod.coerce.string().uuid()
})

export const DeleteAdminStoreCategoryResponse = zod.object({
  "success": zod.boolean()
})


export const ListAdminStoreProductsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "categoryId": zod.string().uuid().nullable(),
  "categoryName": zod.string().nullable(),
  "name": zod.string(),
  "slug": zod.string(),
  "productType": zod.enum(['digital', 'ai_tool']),
  "summary": zod.string().nullable(),
  "description": zod.string().nullable(),
  "features": zod.array(zod.string()),
  "requirements": zod.array(zod.string()),
  "imageUrl": zod.string().url().nullable(),
  "whopProductId": zod.string().nullable(),
  "whopProductUrl": zod.string().url().nullable(),
  "deliveryUrl": zod.string().url().nullable(),
  "deliveryInstructions": zod.string().nullable(),
  "status": zod.enum(['draft', 'published', 'archived']),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})
export const ListAdminStoreProductsResponse = zod.array(ListAdminStoreProductsResponseItem)


export const createAdminStoreProductBodyNameMax = 200;

export const createAdminStoreProductBodySlugMax = 200;


export const createAdminStoreProductBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)*$');
export const createAdminStoreProductBodySummaryMax = 500;

export const createAdminStoreProductBodyDescriptionMax = 10000;

export const createAdminStoreProductBodyFeaturesItemMax = 500;

export const createAdminStoreProductBodyRequirementsItemMax = 500;

export const createAdminStoreProductBodyWhopProductIdMax = 200;

export const createAdminStoreProductBodyDeliveryInstructionsMax = 5000;

export const createAdminStoreProductBodyStatusDefault = `draft`;

export const CreateAdminStoreProductBody = zod.object({
  "categoryId": zod.string().uuid().nullish(),
  "name": zod.string().min(1).max(createAdminStoreProductBodyNameMax),
  "slug": zod.string().max(createAdminStoreProductBodySlugMax).regex(createAdminStoreProductBodySlugRegExp),
  "productType": zod.enum(['digital', 'ai_tool']),
  "summary": zod.string().max(createAdminStoreProductBodySummaryMax).nullish(),
  "description": zod.string().max(createAdminStoreProductBodyDescriptionMax).nullish(),
  "features": zod.array(zod.string().max(createAdminStoreProductBodyFeaturesItemMax)).optional(),
  "requirements": zod.array(zod.string().max(createAdminStoreProductBodyRequirementsItemMax)).optional(),
  "imageUrl": zod.string().url().nullish(),
  "whopProductId": zod.string().max(createAdminStoreProductBodyWhopProductIdMax).nullish(),
  "whopProductUrl": zod.string().url().nullish(),
  "deliveryUrl": zod.string().url().nullish(),
  "deliveryInstructions": zod.string().max(createAdminStoreProductBodyDeliveryInstructionsMax).nullish(),
  "status": zod.enum(['draft', 'published', 'archived']).default(createAdminStoreProductBodyStatusDefault)
})

export const CreateAdminStoreProductResponse = zod.object({
  "id": zod.string().uuid(),
  "categoryId": zod.string().uuid().nullable(),
  "categoryName": zod.string().nullable(),
  "name": zod.string(),
  "slug": zod.string(),
  "productType": zod.enum(['digital', 'ai_tool']),
  "summary": zod.string().nullable(),
  "description": zod.string().nullable(),
  "features": zod.array(zod.string()),
  "requirements": zod.array(zod.string()),
  "imageUrl": zod.string().url().nullable(),
  "whopProductId": zod.string().nullable(),
  "whopProductUrl": zod.string().url().nullable(),
  "deliveryUrl": zod.string().url().nullable(),
  "deliveryInstructions": zod.string().nullable(),
  "status": zod.enum(['draft', 'published', 'archived']),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const GetAdminStoreProductParams = zod.object({
  "id": zod.coerce.string().uuid()
})

export const GetAdminStoreProductResponse = zod.object({
  "id": zod.string().uuid(),
  "categoryId": zod.string().uuid().nullable(),
  "categoryName": zod.string().nullable(),
  "name": zod.string(),
  "slug": zod.string(),
  "productType": zod.enum(['digital', 'ai_tool']),
  "summary": zod.string().nullable(),
  "description": zod.string().nullable(),
  "features": zod.array(zod.string()),
  "requirements": zod.array(zod.string()),
  "imageUrl": zod.string().url().nullable(),
  "whopProductId": zod.string().nullable(),
  "whopProductUrl": zod.string().url().nullable(),
  "deliveryUrl": zod.string().url().nullable(),
  "deliveryInstructions": zod.string().nullable(),
  "status": zod.enum(['draft', 'published', 'archived']),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const UpdateAdminStoreProductParams = zod.object({
  "id": zod.coerce.string().uuid()
})

export const updateAdminStoreProductBodyNameMax = 200;

export const updateAdminStoreProductBodySlugMax = 200;


export const updateAdminStoreProductBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)*$');
export const updateAdminStoreProductBodySummaryMax = 500;

export const updateAdminStoreProductBodyDescriptionMax = 10000;

export const updateAdminStoreProductBodyFeaturesItemMax = 500;

export const updateAdminStoreProductBodyRequirementsItemMax = 500;

export const updateAdminStoreProductBodyWhopProductIdMax = 200;

export const updateAdminStoreProductBodyDeliveryInstructionsMax = 5000;



export const UpdateAdminStoreProductBody = zod.object({
  "categoryId": zod.string().uuid().nullish(),
  "name": zod.string().min(1).max(updateAdminStoreProductBodyNameMax).optional(),
  "slug": zod.string().max(updateAdminStoreProductBodySlugMax).regex(updateAdminStoreProductBodySlugRegExp).optional(),
  "productType": zod.enum(['digital', 'ai_tool']).optional(),
  "summary": zod.string().max(updateAdminStoreProductBodySummaryMax).nullish(),
  "description": zod.string().max(updateAdminStoreProductBodyDescriptionMax).nullish(),
  "features": zod.array(zod.string().max(updateAdminStoreProductBodyFeaturesItemMax)).optional(),
  "requirements": zod.array(zod.string().max(updateAdminStoreProductBodyRequirementsItemMax)).optional(),
  "imageUrl": zod.string().url().nullish(),
  "whopProductId": zod.string().max(updateAdminStoreProductBodyWhopProductIdMax).nullish(),
  "whopProductUrl": zod.string().url().nullish(),
  "deliveryUrl": zod.string().url().nullish(),
  "deliveryInstructions": zod.string().max(updateAdminStoreProductBodyDeliveryInstructionsMax).nullish(),
  "status": zod.enum(['draft', 'published', 'archived']).optional()
})

export const UpdateAdminStoreProductResponse = zod.object({
  "id": zod.string().uuid(),
  "categoryId": zod.string().uuid().nullable(),
  "categoryName": zod.string().nullable(),
  "name": zod.string(),
  "slug": zod.string(),
  "productType": zod.enum(['digital', 'ai_tool']),
  "summary": zod.string().nullable(),
  "description": zod.string().nullable(),
  "features": zod.array(zod.string()),
  "requirements": zod.array(zod.string()),
  "imageUrl": zod.string().url().nullable(),
  "whopProductId": zod.string().nullable(),
  "whopProductUrl": zod.string().url().nullable(),
  "deliveryUrl": zod.string().url().nullable(),
  "deliveryInstructions": zod.string().nullable(),
  "status": zod.enum(['draft', 'published', 'archived']),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const DeleteAdminStoreProductParams = zod.object({
  "id": zod.coerce.string().uuid()
})

export const DeleteAdminStoreProductResponse = zod.object({
  "success": zod.boolean()
})


export const submitStoreSupportTicketBodyNameMax = 160;

export const submitStoreSupportTicketBodyEmailMax = 254;

export const submitStoreSupportTicketBodySubjectMax = 240;

export const submitStoreSupportTicketBodyMessageMax = 10000;



export const SubmitStoreSupportTicketBody = zod.object({
  "name": zod.string().min(1).max(submitStoreSupportTicketBodyNameMax),
  "email": zod.string().email().max(submitStoreSupportTicketBodyEmailMax),
  "subject": zod.string().min(1).max(submitStoreSupportTicketBodySubjectMax),
  "message": zod.string().min(1).max(submitStoreSupportTicketBodyMessageMax),
  "productId": zod.string().uuid().nullish()
})

export const SubmitStoreSupportTicketResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "email": zod.string().email(),
  "subject": zod.string(),
  "message": zod.string(),
  "productId": zod.string().uuid().nullable(),
  "status": zod.enum(['new', 'open', 'answered', 'closed']),
  "adminReply": zod.string().nullable(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const ListAdminStoreSupportTicketsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "email": zod.string().email(),
  "subject": zod.string(),
  "message": zod.string(),
  "productId": zod.string().uuid().nullable(),
  "status": zod.enum(['new', 'open', 'answered', 'closed']),
  "adminReply": zod.string().nullable(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})
export const ListAdminStoreSupportTicketsResponse = zod.array(ListAdminStoreSupportTicketsResponseItem)


export const UpdateAdminStoreSupportTicketParams = zod.object({
  "id": zod.coerce.string().uuid()
})

export const updateAdminStoreSupportTicketBodyAdminReplyMax = 10000;



export const UpdateAdminStoreSupportTicketBody = zod.object({
  "status": zod.enum(['new', 'open', 'answered', 'closed']).optional(),
  "adminReply": zod.string().max(updateAdminStoreSupportTicketBodyAdminReplyMax).nullish()
})

export const UpdateAdminStoreSupportTicketResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "email": zod.string().email(),
  "subject": zod.string(),
  "message": zod.string(),
  "productId": zod.string().uuid().nullable(),
  "status": zod.enum(['new', 'open', 'answered', 'closed']),
  "adminReply": zod.string().nullable(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const GetTuzakaiSiteSettingsResponse = zod.object({
  "websiteUrl": zod.string(),
  "supportEmail": zod.string().nullable(),
  "businessEmail": zod.string().nullable(),
  "socialLinks": zod.object({
  "instagram": zod.string().nullable(),
  "facebook": zod.string().nullable(),
  "pinterest": zod.string().nullable(),
  "youtube": zod.string().nullable(),
  "tiktok": zod.string().nullable()
})
})


export const GetTuzakaiAdminSettingsResponse = zod.object({
  "websiteUrl": zod.string(),
  "supportEmail": zod.string().nullable(),
  "businessEmail": zod.string().nullable(),
  "socialLinks": zod.object({
  "instagram": zod.string().nullable(),
  "facebook": zod.string().nullable(),
  "pinterest": zod.string().nullable(),
  "youtube": zod.string().nullable(),
  "tiktok": zod.string().nullable()
}),
  "updatedAt": zod.coerce.date()
})


export const updateTuzakaiAdminSettingsBodyWebsiteUrlMax = 300;

export const updateTuzakaiAdminSettingsBodySupportEmailMax = 254;

export const updateTuzakaiAdminSettingsBodyBusinessEmailMax = 254;



export const UpdateTuzakaiAdminSettingsBody = zod.object({
  "websiteUrl": zod.string().url().max(updateTuzakaiAdminSettingsBodyWebsiteUrlMax),
  "supportEmail": zod.string().max(updateTuzakaiAdminSettingsBodySupportEmailMax).nullable(),
  "businessEmail": zod.string().max(updateTuzakaiAdminSettingsBodyBusinessEmailMax).nullable(),
  "socialLinks": zod.object({
  "instagram": zod.string().nullable(),
  "facebook": zod.string().nullable(),
  "pinterest": zod.string().nullable(),
  "youtube": zod.string().nullable(),
  "tiktok": zod.string().nullable()
})
})

export const UpdateTuzakaiAdminSettingsResponse = zod.object({
  "websiteUrl": zod.string(),
  "supportEmail": zod.string().nullable(),
  "businessEmail": zod.string().nullable(),
  "socialLinks": zod.object({
  "instagram": zod.string().nullable(),
  "facebook": zod.string().nullable(),
  "pinterest": zod.string().nullable(),
  "youtube": zod.string().nullable(),
  "tiktok": zod.string().nullable()
}),
  "updatedAt": zod.coerce.date()
})


export const ListTuzakaiComponentsResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "category": zod.string(),
  "jewelryTypes": zod.array(zod.string()),
  "material": zod.string(),
  "color": zod.string(),
  "size": zod.string(),
  "unit": zod.string(),
  "priceCents": zod.number().int().nullable(),
  "supplier": zod.string().nullable(),
  "supplierUrl": zod.string().nullable(),
  "imageUrl": zod.string().nullable(),
  "weightGrams": zod.number().nullable(),
  "inventoryQuantity": zod.number().int().nullable(),
  "notes": zod.string(),
  "active": zod.boolean()
})
export const ListTuzakaiComponentsResponse = zod.array(ListTuzakaiComponentsResponseItem)










export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputPersonalizationMax = 32;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputBudgetCentsMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputQuantityMax = 100;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputPriceOverridesMinOne = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputWastagePercentMin = 0;
export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputWastagePercentMax = 100;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputLaborMinutesMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputHourlyRateCentsMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputPackagingCentsMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputOtherCentsMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputMarginPercentMin = 0;
export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputMarginPercentMax = 99;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputPlatformFeePercentMin = 0;
export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputPlatformFeePercentMax = 99;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputPaymentFeePercentMin = 0;
export const getTuzakaiOverviewResponseRecentDesignsItemProfileInputPaymentFeePercentMax = 99;









export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPersonalizationMax = 32;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputBudgetCentsMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputQuantityMax = 100;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPriceOverridesMinOne = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputWastagePercentMin = 0;
export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputWastagePercentMax = 100;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputLaborMinutesMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputHourlyRateCentsMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPackagingCentsMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputOtherCentsMin = 0;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputMarginPercentMin = 0;
export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputMarginPercentMax = 99;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPlatformFeePercentMin = 0;
export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPlatformFeePercentMax = 99;

export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPaymentFeePercentMin = 0;
export const getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPaymentFeePercentMax = 99;



export const GetTuzakaiOverviewResponse = zod.object({
  "designCount": zod.number().int(),
  "recentDesigns": zod.array(zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "profile": zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(getTuzakaiOverviewResponseRecentDesignsItemProfileInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(getTuzakaiOverviewResponseRecentDesignsItemProfileInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputWastagePercentMin).max(getTuzakaiOverviewResponseRecentDesignsItemProfileInputWastagePercentMax),
  "laborMinutes": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputPackagingCentsMin),
  "otherCents": zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputOtherCentsMin),
  "marginPercent": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputMarginPercentMin).max(getTuzakaiOverviewResponseRecentDesignsItemProfileInputMarginPercentMax),
  "platformFeePercent": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputPlatformFeePercentMin).max(getTuzakaiOverviewResponseRecentDesignsItemProfileInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileInputPaymentFeePercentMin).max(getTuzakaiOverviewResponseRecentDesignsItemProfileInputPaymentFeePercentMax)
}),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string()),
  "suggestions": zod.array(zod.string()),
  "warnings": zod.array(zod.string()),
  "variations": zod.array(zod.object({
  "label": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputWastagePercentMin).max(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputWastagePercentMax),
  "laborMinutes": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPackagingCentsMin),
  "otherCents": zod.number().int().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputOtherCentsMin),
  "marginPercent": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputMarginPercentMin).max(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputMarginPercentMax),
  "platformFeePercent": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPlatformFeePercentMin).max(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPaymentFeePercentMin).max(getTuzakaiOverviewResponseRecentDesignsItemProfileVariationsItemInputPaymentFeePercentMax)
}),
  "description": zod.string(),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string())
})),
  "difficulty": zod.string(),
  "estimatedMinutes": zod.number().int(),
  "previewLabel": zod.string()
}),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})),
  "missingCatalogPrices": zod.number().int()
})










export const previewTuzakaiDesignBodyPersonalizationMax = 32;

export const previewTuzakaiDesignBodyBudgetCentsMin = 0;

export const previewTuzakaiDesignBodyQuantityMax = 100;

export const previewTuzakaiDesignBodyPriceOverridesMinOne = 0;

export const previewTuzakaiDesignBodyWastagePercentMin = 0;
export const previewTuzakaiDesignBodyWastagePercentMax = 100;

export const previewTuzakaiDesignBodyLaborMinutesMin = 0;

export const previewTuzakaiDesignBodyHourlyRateCentsMin = 0;

export const previewTuzakaiDesignBodyPackagingCentsMin = 0;

export const previewTuzakaiDesignBodyOtherCentsMin = 0;

export const previewTuzakaiDesignBodyMarginPercentMin = 0;
export const previewTuzakaiDesignBodyMarginPercentMax = 99;

export const previewTuzakaiDesignBodyPlatformFeePercentMin = 0;
export const previewTuzakaiDesignBodyPlatformFeePercentMax = 99;

export const previewTuzakaiDesignBodyPaymentFeePercentMin = 0;
export const previewTuzakaiDesignBodyPaymentFeePercentMax = 99;



export const PreviewTuzakaiDesignBody = zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(previewTuzakaiDesignBodyPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(previewTuzakaiDesignBodyBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(previewTuzakaiDesignBodyQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(previewTuzakaiDesignBodyPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(previewTuzakaiDesignBodyWastagePercentMin).max(previewTuzakaiDesignBodyWastagePercentMax),
  "laborMinutes": zod.number().min(previewTuzakaiDesignBodyLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(previewTuzakaiDesignBodyHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(previewTuzakaiDesignBodyPackagingCentsMin),
  "otherCents": zod.number().int().min(previewTuzakaiDesignBodyOtherCentsMin),
  "marginPercent": zod.number().min(previewTuzakaiDesignBodyMarginPercentMin).max(previewTuzakaiDesignBodyMarginPercentMax),
  "platformFeePercent": zod.number().min(previewTuzakaiDesignBodyPlatformFeePercentMin).max(previewTuzakaiDesignBodyPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(previewTuzakaiDesignBodyPaymentFeePercentMin).max(previewTuzakaiDesignBodyPaymentFeePercentMax)
})









export const previewTuzakaiDesignResponseInputPersonalizationMax = 32;

export const previewTuzakaiDesignResponseInputBudgetCentsMin = 0;

export const previewTuzakaiDesignResponseInputQuantityMax = 100;

export const previewTuzakaiDesignResponseInputPriceOverridesMinOne = 0;

export const previewTuzakaiDesignResponseInputWastagePercentMin = 0;
export const previewTuzakaiDesignResponseInputWastagePercentMax = 100;

export const previewTuzakaiDesignResponseInputLaborMinutesMin = 0;

export const previewTuzakaiDesignResponseInputHourlyRateCentsMin = 0;

export const previewTuzakaiDesignResponseInputPackagingCentsMin = 0;

export const previewTuzakaiDesignResponseInputOtherCentsMin = 0;

export const previewTuzakaiDesignResponseInputMarginPercentMin = 0;
export const previewTuzakaiDesignResponseInputMarginPercentMax = 99;

export const previewTuzakaiDesignResponseInputPlatformFeePercentMin = 0;
export const previewTuzakaiDesignResponseInputPlatformFeePercentMax = 99;

export const previewTuzakaiDesignResponseInputPaymentFeePercentMin = 0;
export const previewTuzakaiDesignResponseInputPaymentFeePercentMax = 99;









export const previewTuzakaiDesignResponseVariationsItemInputPersonalizationMax = 32;

export const previewTuzakaiDesignResponseVariationsItemInputBudgetCentsMin = 0;

export const previewTuzakaiDesignResponseVariationsItemInputQuantityMax = 100;

export const previewTuzakaiDesignResponseVariationsItemInputPriceOverridesMinOne = 0;

export const previewTuzakaiDesignResponseVariationsItemInputWastagePercentMin = 0;
export const previewTuzakaiDesignResponseVariationsItemInputWastagePercentMax = 100;

export const previewTuzakaiDesignResponseVariationsItemInputLaborMinutesMin = 0;

export const previewTuzakaiDesignResponseVariationsItemInputHourlyRateCentsMin = 0;

export const previewTuzakaiDesignResponseVariationsItemInputPackagingCentsMin = 0;

export const previewTuzakaiDesignResponseVariationsItemInputOtherCentsMin = 0;

export const previewTuzakaiDesignResponseVariationsItemInputMarginPercentMin = 0;
export const previewTuzakaiDesignResponseVariationsItemInputMarginPercentMax = 99;

export const previewTuzakaiDesignResponseVariationsItemInputPlatformFeePercentMin = 0;
export const previewTuzakaiDesignResponseVariationsItemInputPlatformFeePercentMax = 99;

export const previewTuzakaiDesignResponseVariationsItemInputPaymentFeePercentMin = 0;
export const previewTuzakaiDesignResponseVariationsItemInputPaymentFeePercentMax = 99;



export const PreviewTuzakaiDesignResponse = zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(previewTuzakaiDesignResponseInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(previewTuzakaiDesignResponseInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(previewTuzakaiDesignResponseInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(previewTuzakaiDesignResponseInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(previewTuzakaiDesignResponseInputWastagePercentMin).max(previewTuzakaiDesignResponseInputWastagePercentMax),
  "laborMinutes": zod.number().min(previewTuzakaiDesignResponseInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(previewTuzakaiDesignResponseInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(previewTuzakaiDesignResponseInputPackagingCentsMin),
  "otherCents": zod.number().int().min(previewTuzakaiDesignResponseInputOtherCentsMin),
  "marginPercent": zod.number().min(previewTuzakaiDesignResponseInputMarginPercentMin).max(previewTuzakaiDesignResponseInputMarginPercentMax),
  "platformFeePercent": zod.number().min(previewTuzakaiDesignResponseInputPlatformFeePercentMin).max(previewTuzakaiDesignResponseInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(previewTuzakaiDesignResponseInputPaymentFeePercentMin).max(previewTuzakaiDesignResponseInputPaymentFeePercentMax)
}),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string()),
  "suggestions": zod.array(zod.string()),
  "warnings": zod.array(zod.string()),
  "variations": zod.array(zod.object({
  "label": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(previewTuzakaiDesignResponseVariationsItemInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(previewTuzakaiDesignResponseVariationsItemInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(previewTuzakaiDesignResponseVariationsItemInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(previewTuzakaiDesignResponseVariationsItemInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(previewTuzakaiDesignResponseVariationsItemInputWastagePercentMin).max(previewTuzakaiDesignResponseVariationsItemInputWastagePercentMax),
  "laborMinutes": zod.number().min(previewTuzakaiDesignResponseVariationsItemInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(previewTuzakaiDesignResponseVariationsItemInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(previewTuzakaiDesignResponseVariationsItemInputPackagingCentsMin),
  "otherCents": zod.number().int().min(previewTuzakaiDesignResponseVariationsItemInputOtherCentsMin),
  "marginPercent": zod.number().min(previewTuzakaiDesignResponseVariationsItemInputMarginPercentMin).max(previewTuzakaiDesignResponseVariationsItemInputMarginPercentMax),
  "platformFeePercent": zod.number().min(previewTuzakaiDesignResponseVariationsItemInputPlatformFeePercentMin).max(previewTuzakaiDesignResponseVariationsItemInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(previewTuzakaiDesignResponseVariationsItemInputPaymentFeePercentMin).max(previewTuzakaiDesignResponseVariationsItemInputPaymentFeePercentMax)
}),
  "description": zod.string(),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string())
})),
  "difficulty": zod.string(),
  "estimatedMinutes": zod.number().int(),
  "previewLabel": zod.string()
})










export const listTuzakaiDesignsResponseProfileInputPersonalizationMax = 32;

export const listTuzakaiDesignsResponseProfileInputBudgetCentsMin = 0;

export const listTuzakaiDesignsResponseProfileInputQuantityMax = 100;

export const listTuzakaiDesignsResponseProfileInputPriceOverridesMinOne = 0;

export const listTuzakaiDesignsResponseProfileInputWastagePercentMin = 0;
export const listTuzakaiDesignsResponseProfileInputWastagePercentMax = 100;

export const listTuzakaiDesignsResponseProfileInputLaborMinutesMin = 0;

export const listTuzakaiDesignsResponseProfileInputHourlyRateCentsMin = 0;

export const listTuzakaiDesignsResponseProfileInputPackagingCentsMin = 0;

export const listTuzakaiDesignsResponseProfileInputOtherCentsMin = 0;

export const listTuzakaiDesignsResponseProfileInputMarginPercentMin = 0;
export const listTuzakaiDesignsResponseProfileInputMarginPercentMax = 99;

export const listTuzakaiDesignsResponseProfileInputPlatformFeePercentMin = 0;
export const listTuzakaiDesignsResponseProfileInputPlatformFeePercentMax = 99;

export const listTuzakaiDesignsResponseProfileInputPaymentFeePercentMin = 0;
export const listTuzakaiDesignsResponseProfileInputPaymentFeePercentMax = 99;









export const listTuzakaiDesignsResponseProfileVariationsItemInputPersonalizationMax = 32;

export const listTuzakaiDesignsResponseProfileVariationsItemInputBudgetCentsMin = 0;

export const listTuzakaiDesignsResponseProfileVariationsItemInputQuantityMax = 100;

export const listTuzakaiDesignsResponseProfileVariationsItemInputPriceOverridesMinOne = 0;

export const listTuzakaiDesignsResponseProfileVariationsItemInputWastagePercentMin = 0;
export const listTuzakaiDesignsResponseProfileVariationsItemInputWastagePercentMax = 100;

export const listTuzakaiDesignsResponseProfileVariationsItemInputLaborMinutesMin = 0;

export const listTuzakaiDesignsResponseProfileVariationsItemInputHourlyRateCentsMin = 0;

export const listTuzakaiDesignsResponseProfileVariationsItemInputPackagingCentsMin = 0;

export const listTuzakaiDesignsResponseProfileVariationsItemInputOtherCentsMin = 0;

export const listTuzakaiDesignsResponseProfileVariationsItemInputMarginPercentMin = 0;
export const listTuzakaiDesignsResponseProfileVariationsItemInputMarginPercentMax = 99;

export const listTuzakaiDesignsResponseProfileVariationsItemInputPlatformFeePercentMin = 0;
export const listTuzakaiDesignsResponseProfileVariationsItemInputPlatformFeePercentMax = 99;

export const listTuzakaiDesignsResponseProfileVariationsItemInputPaymentFeePercentMin = 0;
export const listTuzakaiDesignsResponseProfileVariationsItemInputPaymentFeePercentMax = 99;



export const ListTuzakaiDesignsResponseItem = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "profile": zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(listTuzakaiDesignsResponseProfileInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(listTuzakaiDesignsResponseProfileInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(listTuzakaiDesignsResponseProfileInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(listTuzakaiDesignsResponseProfileInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(listTuzakaiDesignsResponseProfileInputWastagePercentMin).max(listTuzakaiDesignsResponseProfileInputWastagePercentMax),
  "laborMinutes": zod.number().min(listTuzakaiDesignsResponseProfileInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(listTuzakaiDesignsResponseProfileInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(listTuzakaiDesignsResponseProfileInputPackagingCentsMin),
  "otherCents": zod.number().int().min(listTuzakaiDesignsResponseProfileInputOtherCentsMin),
  "marginPercent": zod.number().min(listTuzakaiDesignsResponseProfileInputMarginPercentMin).max(listTuzakaiDesignsResponseProfileInputMarginPercentMax),
  "platformFeePercent": zod.number().min(listTuzakaiDesignsResponseProfileInputPlatformFeePercentMin).max(listTuzakaiDesignsResponseProfileInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(listTuzakaiDesignsResponseProfileInputPaymentFeePercentMin).max(listTuzakaiDesignsResponseProfileInputPaymentFeePercentMax)
}),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string()),
  "suggestions": zod.array(zod.string()),
  "warnings": zod.array(zod.string()),
  "variations": zod.array(zod.object({
  "label": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(listTuzakaiDesignsResponseProfileVariationsItemInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(listTuzakaiDesignsResponseProfileVariationsItemInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(listTuzakaiDesignsResponseProfileVariationsItemInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(listTuzakaiDesignsResponseProfileVariationsItemInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(listTuzakaiDesignsResponseProfileVariationsItemInputWastagePercentMin).max(listTuzakaiDesignsResponseProfileVariationsItemInputWastagePercentMax),
  "laborMinutes": zod.number().min(listTuzakaiDesignsResponseProfileVariationsItemInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(listTuzakaiDesignsResponseProfileVariationsItemInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(listTuzakaiDesignsResponseProfileVariationsItemInputPackagingCentsMin),
  "otherCents": zod.number().int().min(listTuzakaiDesignsResponseProfileVariationsItemInputOtherCentsMin),
  "marginPercent": zod.number().min(listTuzakaiDesignsResponseProfileVariationsItemInputMarginPercentMin).max(listTuzakaiDesignsResponseProfileVariationsItemInputMarginPercentMax),
  "platformFeePercent": zod.number().min(listTuzakaiDesignsResponseProfileVariationsItemInputPlatformFeePercentMin).max(listTuzakaiDesignsResponseProfileVariationsItemInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(listTuzakaiDesignsResponseProfileVariationsItemInputPaymentFeePercentMin).max(listTuzakaiDesignsResponseProfileVariationsItemInputPaymentFeePercentMax)
}),
  "description": zod.string(),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string())
})),
  "difficulty": zod.string(),
  "estimatedMinutes": zod.number().int(),
  "previewLabel": zod.string()
}),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})
export const ListTuzakaiDesignsResponse = zod.array(ListTuzakaiDesignsResponseItem)










export const saveTuzakaiDesignBodyPersonalizationMax = 32;

export const saveTuzakaiDesignBodyBudgetCentsMin = 0;

export const saveTuzakaiDesignBodyQuantityMax = 100;

export const saveTuzakaiDesignBodyPriceOverridesMinOne = 0;

export const saveTuzakaiDesignBodyWastagePercentMin = 0;
export const saveTuzakaiDesignBodyWastagePercentMax = 100;

export const saveTuzakaiDesignBodyLaborMinutesMin = 0;

export const saveTuzakaiDesignBodyHourlyRateCentsMin = 0;

export const saveTuzakaiDesignBodyPackagingCentsMin = 0;

export const saveTuzakaiDesignBodyOtherCentsMin = 0;

export const saveTuzakaiDesignBodyMarginPercentMin = 0;
export const saveTuzakaiDesignBodyMarginPercentMax = 99;

export const saveTuzakaiDesignBodyPlatformFeePercentMin = 0;
export const saveTuzakaiDesignBodyPlatformFeePercentMax = 99;

export const saveTuzakaiDesignBodyPaymentFeePercentMin = 0;
export const saveTuzakaiDesignBodyPaymentFeePercentMax = 99;



export const SaveTuzakaiDesignBody = zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(saveTuzakaiDesignBodyPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(saveTuzakaiDesignBodyBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(saveTuzakaiDesignBodyQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(saveTuzakaiDesignBodyPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(saveTuzakaiDesignBodyWastagePercentMin).max(saveTuzakaiDesignBodyWastagePercentMax),
  "laborMinutes": zod.number().min(saveTuzakaiDesignBodyLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(saveTuzakaiDesignBodyHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(saveTuzakaiDesignBodyPackagingCentsMin),
  "otherCents": zod.number().int().min(saveTuzakaiDesignBodyOtherCentsMin),
  "marginPercent": zod.number().min(saveTuzakaiDesignBodyMarginPercentMin).max(saveTuzakaiDesignBodyMarginPercentMax),
  "platformFeePercent": zod.number().min(saveTuzakaiDesignBodyPlatformFeePercentMin).max(saveTuzakaiDesignBodyPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(saveTuzakaiDesignBodyPaymentFeePercentMin).max(saveTuzakaiDesignBodyPaymentFeePercentMax)
})









export const saveTuzakaiDesignResponseProfileInputPersonalizationMax = 32;

export const saveTuzakaiDesignResponseProfileInputBudgetCentsMin = 0;

export const saveTuzakaiDesignResponseProfileInputQuantityMax = 100;

export const saveTuzakaiDesignResponseProfileInputPriceOverridesMinOne = 0;

export const saveTuzakaiDesignResponseProfileInputWastagePercentMin = 0;
export const saveTuzakaiDesignResponseProfileInputWastagePercentMax = 100;

export const saveTuzakaiDesignResponseProfileInputLaborMinutesMin = 0;

export const saveTuzakaiDesignResponseProfileInputHourlyRateCentsMin = 0;

export const saveTuzakaiDesignResponseProfileInputPackagingCentsMin = 0;

export const saveTuzakaiDesignResponseProfileInputOtherCentsMin = 0;

export const saveTuzakaiDesignResponseProfileInputMarginPercentMin = 0;
export const saveTuzakaiDesignResponseProfileInputMarginPercentMax = 99;

export const saveTuzakaiDesignResponseProfileInputPlatformFeePercentMin = 0;
export const saveTuzakaiDesignResponseProfileInputPlatformFeePercentMax = 99;

export const saveTuzakaiDesignResponseProfileInputPaymentFeePercentMin = 0;
export const saveTuzakaiDesignResponseProfileInputPaymentFeePercentMax = 99;









export const saveTuzakaiDesignResponseProfileVariationsItemInputPersonalizationMax = 32;

export const saveTuzakaiDesignResponseProfileVariationsItemInputBudgetCentsMin = 0;

export const saveTuzakaiDesignResponseProfileVariationsItemInputQuantityMax = 100;

export const saveTuzakaiDesignResponseProfileVariationsItemInputPriceOverridesMinOne = 0;

export const saveTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMin = 0;
export const saveTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMax = 100;

export const saveTuzakaiDesignResponseProfileVariationsItemInputLaborMinutesMin = 0;

export const saveTuzakaiDesignResponseProfileVariationsItemInputHourlyRateCentsMin = 0;

export const saveTuzakaiDesignResponseProfileVariationsItemInputPackagingCentsMin = 0;

export const saveTuzakaiDesignResponseProfileVariationsItemInputOtherCentsMin = 0;

export const saveTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMin = 0;
export const saveTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMax = 99;

export const saveTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMin = 0;
export const saveTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMax = 99;

export const saveTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMin = 0;
export const saveTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMax = 99;



export const SaveTuzakaiDesignResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "profile": zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(saveTuzakaiDesignResponseProfileInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(saveTuzakaiDesignResponseProfileInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(saveTuzakaiDesignResponseProfileInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(saveTuzakaiDesignResponseProfileInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(saveTuzakaiDesignResponseProfileInputWastagePercentMin).max(saveTuzakaiDesignResponseProfileInputWastagePercentMax),
  "laborMinutes": zod.number().min(saveTuzakaiDesignResponseProfileInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(saveTuzakaiDesignResponseProfileInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(saveTuzakaiDesignResponseProfileInputPackagingCentsMin),
  "otherCents": zod.number().int().min(saveTuzakaiDesignResponseProfileInputOtherCentsMin),
  "marginPercent": zod.number().min(saveTuzakaiDesignResponseProfileInputMarginPercentMin).max(saveTuzakaiDesignResponseProfileInputMarginPercentMax),
  "platformFeePercent": zod.number().min(saveTuzakaiDesignResponseProfileInputPlatformFeePercentMin).max(saveTuzakaiDesignResponseProfileInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(saveTuzakaiDesignResponseProfileInputPaymentFeePercentMin).max(saveTuzakaiDesignResponseProfileInputPaymentFeePercentMax)
}),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string()),
  "suggestions": zod.array(zod.string()),
  "warnings": zod.array(zod.string()),
  "variations": zod.array(zod.object({
  "label": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(saveTuzakaiDesignResponseProfileVariationsItemInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(saveTuzakaiDesignResponseProfileVariationsItemInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(saveTuzakaiDesignResponseProfileVariationsItemInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(saveTuzakaiDesignResponseProfileVariationsItemInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(saveTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMin).max(saveTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMax),
  "laborMinutes": zod.number().min(saveTuzakaiDesignResponseProfileVariationsItemInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(saveTuzakaiDesignResponseProfileVariationsItemInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(saveTuzakaiDesignResponseProfileVariationsItemInputPackagingCentsMin),
  "otherCents": zod.number().int().min(saveTuzakaiDesignResponseProfileVariationsItemInputOtherCentsMin),
  "marginPercent": zod.number().min(saveTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMin).max(saveTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMax),
  "platformFeePercent": zod.number().min(saveTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMin).max(saveTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(saveTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMin).max(saveTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMax)
}),
  "description": zod.string(),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string())
})),
  "difficulty": zod.string(),
  "estimatedMinutes": zod.number().int(),
  "previewLabel": zod.string()
}),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const GetTuzakaiDesignParams = zod.object({
  "id": zod.coerce.string().uuid()
})









export const getTuzakaiDesignResponseProfileInputPersonalizationMax = 32;

export const getTuzakaiDesignResponseProfileInputBudgetCentsMin = 0;

export const getTuzakaiDesignResponseProfileInputQuantityMax = 100;

export const getTuzakaiDesignResponseProfileInputPriceOverridesMinOne = 0;

export const getTuzakaiDesignResponseProfileInputWastagePercentMin = 0;
export const getTuzakaiDesignResponseProfileInputWastagePercentMax = 100;

export const getTuzakaiDesignResponseProfileInputLaborMinutesMin = 0;

export const getTuzakaiDesignResponseProfileInputHourlyRateCentsMin = 0;

export const getTuzakaiDesignResponseProfileInputPackagingCentsMin = 0;

export const getTuzakaiDesignResponseProfileInputOtherCentsMin = 0;

export const getTuzakaiDesignResponseProfileInputMarginPercentMin = 0;
export const getTuzakaiDesignResponseProfileInputMarginPercentMax = 99;

export const getTuzakaiDesignResponseProfileInputPlatformFeePercentMin = 0;
export const getTuzakaiDesignResponseProfileInputPlatformFeePercentMax = 99;

export const getTuzakaiDesignResponseProfileInputPaymentFeePercentMin = 0;
export const getTuzakaiDesignResponseProfileInputPaymentFeePercentMax = 99;









export const getTuzakaiDesignResponseProfileVariationsItemInputPersonalizationMax = 32;

export const getTuzakaiDesignResponseProfileVariationsItemInputBudgetCentsMin = 0;

export const getTuzakaiDesignResponseProfileVariationsItemInputQuantityMax = 100;

export const getTuzakaiDesignResponseProfileVariationsItemInputPriceOverridesMinOne = 0;

export const getTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMin = 0;
export const getTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMax = 100;

export const getTuzakaiDesignResponseProfileVariationsItemInputLaborMinutesMin = 0;

export const getTuzakaiDesignResponseProfileVariationsItemInputHourlyRateCentsMin = 0;

export const getTuzakaiDesignResponseProfileVariationsItemInputPackagingCentsMin = 0;

export const getTuzakaiDesignResponseProfileVariationsItemInputOtherCentsMin = 0;

export const getTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMin = 0;
export const getTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMax = 99;

export const getTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMin = 0;
export const getTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMax = 99;

export const getTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMin = 0;
export const getTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMax = 99;



export const GetTuzakaiDesignResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "profile": zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(getTuzakaiDesignResponseProfileInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(getTuzakaiDesignResponseProfileInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(getTuzakaiDesignResponseProfileInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(getTuzakaiDesignResponseProfileInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(getTuzakaiDesignResponseProfileInputWastagePercentMin).max(getTuzakaiDesignResponseProfileInputWastagePercentMax),
  "laborMinutes": zod.number().min(getTuzakaiDesignResponseProfileInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(getTuzakaiDesignResponseProfileInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(getTuzakaiDesignResponseProfileInputPackagingCentsMin),
  "otherCents": zod.number().int().min(getTuzakaiDesignResponseProfileInputOtherCentsMin),
  "marginPercent": zod.number().min(getTuzakaiDesignResponseProfileInputMarginPercentMin).max(getTuzakaiDesignResponseProfileInputMarginPercentMax),
  "platformFeePercent": zod.number().min(getTuzakaiDesignResponseProfileInputPlatformFeePercentMin).max(getTuzakaiDesignResponseProfileInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(getTuzakaiDesignResponseProfileInputPaymentFeePercentMin).max(getTuzakaiDesignResponseProfileInputPaymentFeePercentMax)
}),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string()),
  "suggestions": zod.array(zod.string()),
  "warnings": zod.array(zod.string()),
  "variations": zod.array(zod.object({
  "label": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(getTuzakaiDesignResponseProfileVariationsItemInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(getTuzakaiDesignResponseProfileVariationsItemInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(getTuzakaiDesignResponseProfileVariationsItemInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(getTuzakaiDesignResponseProfileVariationsItemInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(getTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMin).max(getTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMax),
  "laborMinutes": zod.number().min(getTuzakaiDesignResponseProfileVariationsItemInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(getTuzakaiDesignResponseProfileVariationsItemInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(getTuzakaiDesignResponseProfileVariationsItemInputPackagingCentsMin),
  "otherCents": zod.number().int().min(getTuzakaiDesignResponseProfileVariationsItemInputOtherCentsMin),
  "marginPercent": zod.number().min(getTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMin).max(getTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMax),
  "platformFeePercent": zod.number().min(getTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMin).max(getTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(getTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMin).max(getTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMax)
}),
  "description": zod.string(),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string())
})),
  "difficulty": zod.string(),
  "estimatedMinutes": zod.number().int(),
  "previewLabel": zod.string()
}),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const UpdateTuzakaiDesignParams = zod.object({
  "id": zod.coerce.string().uuid()
})









export const updateTuzakaiDesignBodyPersonalizationMax = 32;

export const updateTuzakaiDesignBodyBudgetCentsMin = 0;

export const updateTuzakaiDesignBodyQuantityMax = 100;

export const updateTuzakaiDesignBodyPriceOverridesMinOne = 0;

export const updateTuzakaiDesignBodyWastagePercentMin = 0;
export const updateTuzakaiDesignBodyWastagePercentMax = 100;

export const updateTuzakaiDesignBodyLaborMinutesMin = 0;

export const updateTuzakaiDesignBodyHourlyRateCentsMin = 0;

export const updateTuzakaiDesignBodyPackagingCentsMin = 0;

export const updateTuzakaiDesignBodyOtherCentsMin = 0;

export const updateTuzakaiDesignBodyMarginPercentMin = 0;
export const updateTuzakaiDesignBodyMarginPercentMax = 99;

export const updateTuzakaiDesignBodyPlatformFeePercentMin = 0;
export const updateTuzakaiDesignBodyPlatformFeePercentMax = 99;

export const updateTuzakaiDesignBodyPaymentFeePercentMin = 0;
export const updateTuzakaiDesignBodyPaymentFeePercentMax = 99;



export const UpdateTuzakaiDesignBody = zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(updateTuzakaiDesignBodyPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(updateTuzakaiDesignBodyBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(updateTuzakaiDesignBodyQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(updateTuzakaiDesignBodyPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(updateTuzakaiDesignBodyWastagePercentMin).max(updateTuzakaiDesignBodyWastagePercentMax),
  "laborMinutes": zod.number().min(updateTuzakaiDesignBodyLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(updateTuzakaiDesignBodyHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(updateTuzakaiDesignBodyPackagingCentsMin),
  "otherCents": zod.number().int().min(updateTuzakaiDesignBodyOtherCentsMin),
  "marginPercent": zod.number().min(updateTuzakaiDesignBodyMarginPercentMin).max(updateTuzakaiDesignBodyMarginPercentMax),
  "platformFeePercent": zod.number().min(updateTuzakaiDesignBodyPlatformFeePercentMin).max(updateTuzakaiDesignBodyPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(updateTuzakaiDesignBodyPaymentFeePercentMin).max(updateTuzakaiDesignBodyPaymentFeePercentMax)
})









export const updateTuzakaiDesignResponseProfileInputPersonalizationMax = 32;

export const updateTuzakaiDesignResponseProfileInputBudgetCentsMin = 0;

export const updateTuzakaiDesignResponseProfileInputQuantityMax = 100;

export const updateTuzakaiDesignResponseProfileInputPriceOverridesMinOne = 0;

export const updateTuzakaiDesignResponseProfileInputWastagePercentMin = 0;
export const updateTuzakaiDesignResponseProfileInputWastagePercentMax = 100;

export const updateTuzakaiDesignResponseProfileInputLaborMinutesMin = 0;

export const updateTuzakaiDesignResponseProfileInputHourlyRateCentsMin = 0;

export const updateTuzakaiDesignResponseProfileInputPackagingCentsMin = 0;

export const updateTuzakaiDesignResponseProfileInputOtherCentsMin = 0;

export const updateTuzakaiDesignResponseProfileInputMarginPercentMin = 0;
export const updateTuzakaiDesignResponseProfileInputMarginPercentMax = 99;

export const updateTuzakaiDesignResponseProfileInputPlatformFeePercentMin = 0;
export const updateTuzakaiDesignResponseProfileInputPlatformFeePercentMax = 99;

export const updateTuzakaiDesignResponseProfileInputPaymentFeePercentMin = 0;
export const updateTuzakaiDesignResponseProfileInputPaymentFeePercentMax = 99;









export const updateTuzakaiDesignResponseProfileVariationsItemInputPersonalizationMax = 32;

export const updateTuzakaiDesignResponseProfileVariationsItemInputBudgetCentsMin = 0;

export const updateTuzakaiDesignResponseProfileVariationsItemInputQuantityMax = 100;

export const updateTuzakaiDesignResponseProfileVariationsItemInputPriceOverridesMinOne = 0;

export const updateTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMin = 0;
export const updateTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMax = 100;

export const updateTuzakaiDesignResponseProfileVariationsItemInputLaborMinutesMin = 0;

export const updateTuzakaiDesignResponseProfileVariationsItemInputHourlyRateCentsMin = 0;

export const updateTuzakaiDesignResponseProfileVariationsItemInputPackagingCentsMin = 0;

export const updateTuzakaiDesignResponseProfileVariationsItemInputOtherCentsMin = 0;

export const updateTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMin = 0;
export const updateTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMax = 99;

export const updateTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMin = 0;
export const updateTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMax = 99;

export const updateTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMin = 0;
export const updateTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMax = 99;



export const UpdateTuzakaiDesignResponse = zod.object({
  "id": zod.string().uuid(),
  "name": zod.string(),
  "profile": zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(updateTuzakaiDesignResponseProfileInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(updateTuzakaiDesignResponseProfileInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(updateTuzakaiDesignResponseProfileInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(updateTuzakaiDesignResponseProfileInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(updateTuzakaiDesignResponseProfileInputWastagePercentMin).max(updateTuzakaiDesignResponseProfileInputWastagePercentMax),
  "laborMinutes": zod.number().min(updateTuzakaiDesignResponseProfileInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(updateTuzakaiDesignResponseProfileInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(updateTuzakaiDesignResponseProfileInputPackagingCentsMin),
  "otherCents": zod.number().int().min(updateTuzakaiDesignResponseProfileInputOtherCentsMin),
  "marginPercent": zod.number().min(updateTuzakaiDesignResponseProfileInputMarginPercentMin).max(updateTuzakaiDesignResponseProfileInputMarginPercentMax),
  "platformFeePercent": zod.number().min(updateTuzakaiDesignResponseProfileInputPlatformFeePercentMin).max(updateTuzakaiDesignResponseProfileInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(updateTuzakaiDesignResponseProfileInputPaymentFeePercentMin).max(updateTuzakaiDesignResponseProfileInputPaymentFeePercentMax)
}),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string()),
  "suggestions": zod.array(zod.string()),
  "warnings": zod.array(zod.string()),
  "variations": zod.array(zod.object({
  "label": zod.string(),
  "input": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(updateTuzakaiDesignResponseProfileVariationsItemInputPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(updateTuzakaiDesignResponseProfileVariationsItemInputBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(updateTuzakaiDesignResponseProfileVariationsItemInputQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(updateTuzakaiDesignResponseProfileVariationsItemInputPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(updateTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMin).max(updateTuzakaiDesignResponseProfileVariationsItemInputWastagePercentMax),
  "laborMinutes": zod.number().min(updateTuzakaiDesignResponseProfileVariationsItemInputLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(updateTuzakaiDesignResponseProfileVariationsItemInputHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(updateTuzakaiDesignResponseProfileVariationsItemInputPackagingCentsMin),
  "otherCents": zod.number().int().min(updateTuzakaiDesignResponseProfileVariationsItemInputOtherCentsMin),
  "marginPercent": zod.number().min(updateTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMin).max(updateTuzakaiDesignResponseProfileVariationsItemInputMarginPercentMax),
  "platformFeePercent": zod.number().min(updateTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMin).max(updateTuzakaiDesignResponseProfileVariationsItemInputPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(updateTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMin).max(updateTuzakaiDesignResponseProfileVariationsItemInputPaymentFeePercentMax)
}),
  "description": zod.string(),
  "materials": zod.array(zod.object({
  "componentId": zod.string(),
  "name": zod.string(),
  "quantity": zod.number(),
  "unit": zod.string(),
  "unitPriceCents": zod.number().int().nullable(),
  "lineCostCents": zod.number().int().nullable(),
  "priceSource": zod.enum(['configured', 'entered', 'missing'])
})),
  "cost": zod.object({
  "rawMaterialsCents": zod.number().int().nullable(),
  "wastageCents": zod.number().int().nullable(),
  "laborCents": zod.number().int(),
  "packagingCents": zod.number().int(),
  "otherCents": zod.number().int(),
  "productionCents": zod.number().int().nullable(),
  "suggestedRetailCents": zod.number().int().nullable(),
  "estimatedProfitCents": zod.number().int().nullable(),
  "budgetRemainingCents": zod.number().int().nullable(),
  "currency": zod.enum(['PKR'])
}),
  "instructions": zod.array(zod.string())
})),
  "difficulty": zod.string(),
  "estimatedMinutes": zod.number().int(),
  "previewLabel": zod.string()
}),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


export const DeleteTuzakaiDesignParams = zod.object({
  "id": zod.coerce.string().uuid()
})

export const DeleteTuzakaiDesignResponse = zod.object({
  "success": zod.boolean()
})


export const askTuzakaiAssistantBodyQuestionMin = 3;
export const askTuzakaiAssistantBodyQuestionMax = 2000;









export const askTuzakaiAssistantBodyDesignPersonalizationMax = 32;

export const askTuzakaiAssistantBodyDesignBudgetCentsMin = 0;

export const askTuzakaiAssistantBodyDesignQuantityMax = 100;

export const askTuzakaiAssistantBodyDesignPriceOverridesMinOne = 0;

export const askTuzakaiAssistantBodyDesignWastagePercentMin = 0;
export const askTuzakaiAssistantBodyDesignWastagePercentMax = 100;

export const askTuzakaiAssistantBodyDesignLaborMinutesMin = 0;

export const askTuzakaiAssistantBodyDesignHourlyRateCentsMin = 0;

export const askTuzakaiAssistantBodyDesignPackagingCentsMin = 0;

export const askTuzakaiAssistantBodyDesignOtherCentsMin = 0;

export const askTuzakaiAssistantBodyDesignMarginPercentMin = 0;
export const askTuzakaiAssistantBodyDesignMarginPercentMax = 99;

export const askTuzakaiAssistantBodyDesignPlatformFeePercentMin = 0;
export const askTuzakaiAssistantBodyDesignPlatformFeePercentMax = 99;

export const askTuzakaiAssistantBodyDesignPaymentFeePercentMin = 0;
export const askTuzakaiAssistantBodyDesignPaymentFeePercentMax = 99;



export const AskTuzakaiAssistantBody = zod.object({
  "question": zod.string().min(askTuzakaiAssistantBodyQuestionMin).max(askTuzakaiAssistantBodyQuestionMax),
  "design": zod.object({
  "jewelryType": zod.string().min(1),
  "style": zod.string().min(1),
  "shape": zod.string().min(1),
  "material": zod.string().min(1),
  "color": zod.string().min(1),
  "decoration": zod.string().min(1),
  "finding": zod.string().min(1),
  "size": zod.string().min(1),
  "personalization": zod.string().max(askTuzakaiAssistantBodyDesignPersonalizationMax).optional(),
  "budgetCents": zod.number().int().min(askTuzakaiAssistantBodyDesignBudgetCentsMin).nullish(),
  "quantity": zod.number().int().min(1).max(askTuzakaiAssistantBodyDesignQuantityMax),
  "priceOverrides": zod.record(zod.string(), zod.number().int().min(askTuzakaiAssistantBodyDesignPriceOverridesMinOne)),
  "wastagePercent": zod.number().min(askTuzakaiAssistantBodyDesignWastagePercentMin).max(askTuzakaiAssistantBodyDesignWastagePercentMax),
  "laborMinutes": zod.number().min(askTuzakaiAssistantBodyDesignLaborMinutesMin),
  "hourlyRateCents": zod.number().int().min(askTuzakaiAssistantBodyDesignHourlyRateCentsMin),
  "packagingCents": zod.number().int().min(askTuzakaiAssistantBodyDesignPackagingCentsMin),
  "otherCents": zod.number().int().min(askTuzakaiAssistantBodyDesignOtherCentsMin),
  "marginPercent": zod.number().min(askTuzakaiAssistantBodyDesignMarginPercentMin).max(askTuzakaiAssistantBodyDesignMarginPercentMax),
  "platformFeePercent": zod.number().min(askTuzakaiAssistantBodyDesignPlatformFeePercentMin).max(askTuzakaiAssistantBodyDesignPlatformFeePercentMax),
  "paymentFeePercent": zod.number().min(askTuzakaiAssistantBodyDesignPaymentFeePercentMin).max(askTuzakaiAssistantBodyDesignPaymentFeePercentMax)
}).optional()
})

export const AskTuzakaiAssistantResponse = zod.object({
  "answer": zod.string()
})


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


