/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { JewelryCostCurrency } from './jewelryCostCurrency';

export interface JewelryCost {
  /** @nullable */
  rawMaterialsCents: number | null;
  /** @nullable */
  wastageCents: number | null;
  laborCents: number;
  packagingCents: number;
  otherCents: number;
  /** @nullable */
  productionCents: number | null;
  /** @nullable */
  suggestedRetailCents: number | null;
  /** @nullable */
  estimatedProfitCents: number | null;
  /** @nullable */
  budgetRemainingCents: number | null;
  currency: JewelryCostCurrency;
}
