/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { JewelryMaterialLinePriceSource } from './jewelryMaterialLinePriceSource';

export interface JewelryMaterialLine {
  componentId: string;
  name: string;
  quantity: number;
  unit: string;
  /** @nullable */
  unitPriceCents: number | null;
  /** @nullable */
  lineCostCents: number | null;
  priceSource: JewelryMaterialLinePriceSource;
}
