/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { JewelryCost } from './jewelryCost';
import type { JewelryDesignInput } from './jewelryDesignInput';
import type { JewelryMaterialLine } from './jewelryMaterialLine';
import type { JewelryVariation } from './jewelryVariation';

export interface JewelryDesignProfile {
  name: string;
  description: string;
  input: JewelryDesignInput;
  materials: JewelryMaterialLine[];
  cost: JewelryCost;
  instructions: string[];
  suggestions: string[];
  warnings: string[];
  variations: JewelryVariation[];
  difficulty: string;
  estimatedMinutes: number;
  previewLabel: string;
}
