/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { JewelryDesignInputPriceOverrides } from './jewelryDesignInputPriceOverrides';

export interface JewelryDesignInput {
  /** @minLength 1 */
  jewelryType: string;
  /** @minLength 1 */
  style: string;
  /** @minLength 1 */
  shape: string;
  /** @minLength 1 */
  material: string;
  /** @minLength 1 */
  color: string;
  /** @minLength 1 */
  decoration: string;
  /** @minLength 1 */
  finding: string;
  /** @minLength 1 */
  size: string;
  /** @maxLength 32 */
  personalization?: string;
  /**
     * @minimum 0
     * @nullable
     */
  budgetCents?: number | null;
  /**
     * @minimum 1
     * @maximum 100
     */
  quantity: number;
  priceOverrides: JewelryDesignInputPriceOverrides;
  /**
     * @minimum 0
     * @maximum 100
     */
  wastagePercent: number;
  /** @minimum 0 */
  laborMinutes: number;
  /** @minimum 0 */
  hourlyRateCents: number;
  /** @minimum 0 */
  packagingCents: number;
  /** @minimum 0 */
  otherCents: number;
  /**
     * @minimum 0
     * @maximum 99
     */
  marginPercent: number;
  /**
     * @minimum 0
     * @maximum 99
     */
  platformFeePercent: number;
  /**
     * @minimum 0
     * @maximum 99
     */
  paymentFeePercent: number;
}
