/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type JewelryCostCurrency = typeof JewelryCostCurrency[keyof typeof JewelryCostCurrency];


export const JewelryCostCurrency = {
  PKR: 'PKR',
} as const;
