/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type JewelryMaterialLinePriceSource = typeof JewelryMaterialLinePriceSource[keyof typeof JewelryMaterialLinePriceSource];


export const JewelryMaterialLinePriceSource = {
  configured: 'configured',
  entered: 'entered',
  missing: 'missing',
} as const;
