/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { JewelryDesignInput } from './jewelryDesignInput';

export interface JewelryAssistantInput {
  /**
     * @minLength 3
     * @maxLength 2000
     */
  question: string;
  design?: JewelryDesignInput;
}
