/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface JewelryComponent {
  id: string;
  name: string;
  category: string;
  jewelryTypes: string[];
  material: string;
  color: string;
  size: string;
  unit: string;
  /** @nullable */
  priceCents: number | null;
  /** @nullable */
  supplier: string | null;
  /** @nullable */
  supplierUrl: string | null;
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  weightGrams: number | null;
  /** @nullable */
  inventoryQuantity: number | null;
  notes: string;
  active: boolean;
}
