/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { JewelryDesignProfile } from './jewelryDesignProfile';

export interface SavedJewelryDesign {
  id: string;
  name: string;
  profile: JewelryDesignProfile;
  createdAt: Date;
  updatedAt: Date;
}
