/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type SearchStoreProductsParams = {
/**
 * @minLength 1
 * @maxLength 200
 */
q: string;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
