import { useState, type FormEvent, type ReactNode } from 'react';
import { useParams } from 'wouter';
import { ArrowRight, ArrowUpRight, Search, RefreshCw, ShoppingBag, Layers3, Sparkles, PackageOpen, SlidersHorizontal } from 'lucide-react';
import { useListStoreProducts, useListStoreCategories, useGetStoreProduct, useSearchStoreProducts, getGetStoreProductQueryKey, getSearchStoreProductsQueryKey, type StoreProduct } from '@workspace/api-client-react';
import { SiteLink as Link, ToolCard, toolLinks } from '../components/site';

const useProducts = () => useListStoreProducts({ limit: 100 });
const useCategories = () => useListStoreCategories();
const useProduct = (slug: string) => useGetStoreProduct(slug, { query: { enabled: !!slug, queryKey: getGetStoreProductQueryKey(slug), retry: (count, error) => statusOf(error) !== 404 && count < 2 } });
const statusOf = (error: unknown) => error && typeof error === 'object' && 'status' in error ? Number(error.status) : undefined;
const useSearch = (query: string) => useSearchStoreProducts({ q: query }, { query: { enabled: !!query, queryKey: getSearchStoreProductsQueryKey({ q: query }) } });

function PageIntro({ index, label, title, description, children }: { index: string; label: string; title: string; description: string; children?: ReactNode }) {
  return <div className="store-page-intro"><div className="store-container"><div className="store-overline"><span>{index} / {label}</span><span>TUZAKAI BY SZTUZK</span></div><div className="store-intro-row"><div><h1>{title}</h1><p>{description}</p></div>{children}</div></div></div>;
}
function SectionTitle({ index, title, aside }: { index: string; title: string; aside?: string }) {
  return <div className="store-section-heading"><div><span className="store-kicker">{index}</span><h2>{title}</h2></div>{aside && <p>{aside}</p>}</div>;
}
function StateSkeleton() {
  return <div className="store-product-grid" role="status" aria-label="Loading products">{[0, 1, 2, 3].map(i => <div className="store-skeleton" key={i}><div/><span/><span/></div>)}</div>;
}
function StateError({ retry }: { retry: () => void }) {
  return <div className="store-state" role="alert"><span className="store-state-mark">!</span><h2>We couldn't load the collection.</h2><p>The catalog is temporarily out of reach. Give it another try, or explore the available tools.</p><div className="store-state-actions"><button className="store-button store-button-dark" onClick={retry} data-testid="button-retry-products"><RefreshCw size={16}/> Try again</button><Link href="/ai-tools" className="store-button store-button-outline">Explore tools <ArrowRight size={16}/></Link></div></div>;
}
function StateEmpty({ title = 'The collection is taking shape.', description = 'There are no published products here yet. The tools are ready to explore while the catalog grows.' }: { title?: string; description?: string }) {
  return <div className="store-state"><span className="store-state-mark"><PackageOpen size={31} strokeWidth={1.4}/></span><span className="store-kicker">NOTHING PUBLISHED YET</span><h2>{title}</h2><p>{description}</p><div className="store-state-actions"><Link href="/ai-tools" className="store-button store-button-dark">Explore available tools <ArrowRight size={16}/></Link><Link href="/categories" className="store-button store-button-outline">Browse categories</Link></div></div>;
}
function ProductCard({ product }: { product: StoreProduct }) {
  const category = product.categoryName;
  const image = product.imageUrl;
  return <Link href={`/products/${encodeURIComponent(product.slug)}`} className="store-product-card" data-testid={`card-product-${product.slug}`}>
    <div className="store-product-art">{image ? <img src={image} alt="" loading="lazy"/> : <div className="store-product-art-fallback"><Layers3 size={34} strokeWidth={1.2}/><span>TUZAKAI / DIGITAL WORK</span></div>}<span className="store-product-open" aria-hidden="true"><ArrowUpRight size={21}/></span></div>
    <div className="store-product-meta"><span>{category || (product.productType === 'ai_tool' ? 'AI tool' : 'Digital product')}</span><ArrowRight size={16}/></div><h3>{product.name}</h3><p>{product.summary || product.description || 'Explore the details of this resource.'}</p>
  </Link>;
}
function ProductCollection({ products, loading, error, retry, emptyTitle }: { products?: StoreProduct[]; loading: boolean; error: boolean; retry: () => void; emptyTitle?: string }) {
  if (loading) return <StateSkeleton/>;
  if (error) return <StateError retry={retry}/>;
  if (!products?.length) return <StateEmpty title={emptyTitle}/>;
  return <div className="store-product-grid">{products.filter(p => p.slug && p.name).map(p => <ProductCard key={p.id ?? p.slug} product={p}/>)}</div>;
}
const categoryMatch = (product: StoreProduct, term: string) => {
  const category = `${product.categoryName ?? ''} ${product.categoryId ?? ''}`;
  return `${category} ${product.productType === 'ai_tool' ? 'ai' : 'digital'}`.toLowerCase().includes(term.replaceAll('-', ' '));
};

export function HomePage() {
  const products = useProducts();
  return <div className="storefront">
    <section className="store-hero"><div className="store-hero-copy"><div className="store-kicker store-hero-kicker"><span className="store-asterisk" aria-hidden="true"></span> YOUR CREATIVE BUSINESS, IN MOTION</div><h1>AI Tools &amp; Digital Products <em>for Creative Entrepreneurs</em></h1><p>Create smarter, design faster and grow your digital business with practical AI tools and ready-to-use digital products.</p><div className="store-hero-actions"><Link href="/shop" className="store-button store-button-dark" data-testid="link-hero-shop">Explore the shop <ArrowUpRight size={18}/></Link><Link href="/ai-tools" className="store-text-link" data-testid="link-hero-tools">See the tools <ArrowRight size={17}/></Link></div><div className="store-hero-foot"><span>01 / DISCOVER</span><span>IDEAS NEED A PLACE TO GO.</span></div></div><div className="store-hero-art"><img src="/creative-still-life.png" alt="Sculptural arrangement of colorful studio materials and geometric forms"/><div className="store-art-tag"><span>THE CREATIVE EDITION</span><strong>Tools for the<br/>doing part.</strong></div></div></section>
    <div className="store-marquee" aria-hidden="true"><span>MAKE IT REAL</span><i></i><span>MAKE IT YOURS</span><i></i><span>MAKE IT MOVE</span><i></i><span>MAKE IT REAL</span></div>
    <section className="store-section store-container"><SectionTitle index="01 / CHOOSE YOUR PATH" title="Find your next move." aside="From the first spark to the practical next step. Explore what helps you make progress today."/><div className="store-path-grid"><Link href="/ai-tools" className="store-path-card store-path-primary" data-testid="link-path-ai"><span>01 — CREATE & EXPLORE</span><Sparkles size={32} strokeWidth={1.4}/><h3>AI tools,<br/>real momentum.</h3><p>Move beyond the blank page with tools built for creative work and business decisions.</p><span className="store-path-action">Explore AI tools <ArrowUpRight size={18}/></span></Link><Link href="/digital-products" className="store-path-card store-path-secondary" data-testid="link-path-digital"><span>02 — DOWNLOAD & DO</span><Layers3 size={32} strokeWidth={1.4}/><h3>Resources that<br/>get to work.</h3><p>Browse the digital product collection as new resources become available.</p><span className="store-path-action">Digital products <ArrowUpRight size={18}/></span></Link></div></section>
    <section className="store-feature"><div className="store-container store-feature-inner"><div className="store-feature-visual"><img src="/creative-detail.png" alt="Colorful paper and acrylic design objects in a studio still life"/><span>THE TOOL SPOTLIGHT / 001</span></div><div className="store-feature-copy"><span className="store-kicker">THE FIRST TOOL TO TRY</span><h2>Start with an idea. <em>See where it goes.</em></h2><p>Step inside the TuzakAI Jewelry Designer to explore directions, experiment with details, and turn a starting thought into a visual concept. Jewelry is our starting point, not the limit of what comes next.</p><Link href="/tuzakai/" className="store-button store-button-light" data-testid="link-featured-designer">Open the designer <ArrowUpRight size={18}/></Link><small>Creative exploration only. Review generated results before using them.</small></div></div></section>
    <section className="store-section store-container"><SectionTitle index="02 / THE COLLECTION" title="Worth a closer look." aside="Published products from the live collection appear here. No previews masquerading as products."/><ProductCollection products={products.data?.slice(0, 4)} loading={products.isLoading} error={products.isError} retry={() => void products.refetch()}/><div className="store-section-end"><Link href="/shop" className="store-text-link">Browse the whole shop <ArrowRight size={18}/></Link></div></section>
    <section className="store-note-band"><div className="store-container"><span className="store-kicker">A NOTE FROM THE STUDIO</span><p>Good ideas are a beginning.<br/><em>Good tools help you keep going.</em></p><Link href="/about" className="store-text-link">Get to know TuzakAI <ArrowUpRight size={17}/></Link></div></section>
    <section className="store-section store-container"><SectionTitle index="03 / ALSO IN THE STUDIO" title="Practical tools, ready now." aside="The original Studio remains open, with focused tools for making, pricing, planning and writing."/><div className="store-tool-grid">{toolLinks.slice(0, 3).map(item => <ToolCard key={item.path} item={item}/>)}</div><div className="store-section-end"><Link href="/ai-tools" className="store-text-link">View all tools <ArrowRight size={18}/></Link></div></section>
    <section className="store-bottom-cta"><div className="store-container"><span className="store-kicker">YOUR NEXT MOVE STARTS HERE</span><h2>Make space for<br/><em>what's next.</em></h2><div><Link href="/shop" className="store-button store-button-light">Explore the shop <ArrowUpRight size={18}/></Link><Link href="/categories" className="store-text-link">Browse categories <ArrowRight size={17}/></Link></div></div></section>
  </div>;
}
export function ShopPage() {
  const category = new URLSearchParams(window.location.search).get('category');
  const products = useListStoreProducts({ category: category || undefined, limit: 100 });
  const [filter, setFilter] = useState('all');
  const filtered = products.data?.filter(p => category || filter === 'all' || categoryMatch(p, filter));
  return <div className="storefront"><PageIntro index="01" label="THE SHOP" title="A better way to get things done." description="Explore the published tools and digital products built for curious, independent creative businesses."/><div className="store-container store-section"><div className="store-list-toolbar"><div className="store-filter-label"><SlidersHorizontal size={17}/> {category ? `CATEGORY / ${category.replaceAll('-', ' ')}` : 'BROWSE THE COLLECTION'}</div><div className="store-filters" role="group" aria-label="Filter products">{[['all','All'],['ai','AI tools'],['digital','Digital products']].map(([key,label]) => <button type="button" key={key} className={!category && filter === key ? 'active' : ''} aria-pressed={!category && filter === key} onClick={() => { if (category) window.history.replaceState(null, '', '/shop'); setFilter(key); }} data-testid={`button-filter-${key}`}>{label}</button>)}</div></div><ProductCollection products={filtered} loading={products.isLoading} error={products.isError} retry={() => void products.refetch()} emptyTitle={category ? 'No products published in this category yet.' : filter === 'all' ? undefined : `No ${filter === 'ai' ? 'AI tools' : 'digital products'} published yet.`}/></div></div>;
}
export function DigitalPage() {
  const products = useProducts();
  return <div className="storefront"><PageIntro index="02" label="DIGITAL PRODUCTS" title="Ready when your idea is." description="Practical resources for the work behind a creative business. Only published products appear below."><Link href="/shop" className="store-text-link">All products <ArrowUpRight size={17}/></Link></PageIntro><div className="store-container store-section"><SectionTitle index="THE COLLECTION" title="Digital products."/><ProductCollection products={products.data?.filter(p => categoryMatch(p, 'digital'))} loading={products.isLoading} error={products.isError} retry={() => void products.refetch()}/></div></div>;
}
export function AIToolsPage() {
  const products = useProducts();
  return <div className="storefront"><PageIntro index="03" label="AI TOOLS" title="Move the idea forward." description="Explore tools for creative momentum, plus the original Studio's practical planning utilities."/ ><section className="store-container store-section"><div className="store-tool-spotlight"><div><span className="store-kicker">FEATURED / CREATIVE EXPLORATION</span><h2>TuzakAI Jewelry Designer</h2><p>Find a direction for your next jewelry concept with the dedicated designer. Explore ideas, then make the details your own.</p><Link href="/tuzakai/" className="store-button store-button-dark" data-testid="link-ai-designer">Open the designer <ArrowUpRight size={17}/></Link></div><div className="store-tool-spotlight-art"><img src="/creative-detail.png" alt="Abstract studio objects in cobalt, coral and cream"/></div></div></section><section className="store-container store-section store-section-tight"><SectionTitle index="PUBLISHED TOOLS" title="Explore the collection."/><ProductCollection products={products.data?.filter(p => categoryMatch(p, 'ai'))} loading={products.isLoading} error={products.isError} retry={() => void products.refetch()}/></section><section className="store-container store-section store-section-tight"><SectionTitle index="THE ORIGINAL STUDIO" title="Five focused ways to begin." aside="These original tools remain available at their existing links. Outputs are drafts and estimates to review, not finished decisions."/><div className="store-tool-grid">{toolLinks.map(item => <ToolCard key={item.path} item={item}/>)}</div><p className="store-disclaimer">The original Studio generators are rule-based; not every tool on this page uses AI.</p></section></div>;
}
export function CategoriesPage() {
  const categories = useCategories();
  return <div className="storefront"><PageIntro index="04" label="CATEGORIES" title="Follow your curiosity." description="Browse the live catalog by category, or head straight to the tools already available."/ ><div className="store-container store-section">{categories.isLoading ? <StateSkeleton/> : categories.isError ? <StateError retry={() => void categories.refetch()}/> : categories.data?.length ? <div className="store-category-grid">{categories.data.filter(c => c.slug && c.name).map((c, i) => <Link key={c.id ?? c.slug} href={`/shop?category=${encodeURIComponent(c.slug)}`} className="store-category-tile" data-testid={`link-category-${c.slug}`}><span>{String(i + 1).padStart(2, '0')} / CATEGORY</span><h2>{c.name}</h2><p>{c.description || 'Explore the collection.'}</p><ArrowUpRight size={24}/></Link>)}</div> : <StateEmpty title="Categories are being curated." description="There are no published categories yet. Explore the available tools while the collection takes shape."/>}<div className="store-section-end"><Link href="/ai-tools" className="store-text-link">Explore available tools <ArrowRight size={17}/></Link></div></div></div>;
}
export function SearchPage() {
  const [input, setInput] = useState('');
  const [query, setQuery] = useState('');
  const search = useSearch(query);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setQuery(input.trim()); };
  return <div className="storefront"><PageIntro index="05" label="SEARCH" title="Find your way in." description="Search the published collection for the right resource to move your work forward."/ ><div className="store-container store-section"><form className="store-search-form" onSubmit={submit}><Search size={25}/><input value={input} onChange={e => setInput(e.target.value)} type="search" aria-label="Search products" placeholder="What are you working on?" data-testid="input-site-search"/><button type="submit" className="store-button store-button-dark" data-testid="button-search">Search <ArrowRight size={17}/></button></form>{query ? <><div className="store-list-toolbar"><span className="store-kicker" role="status" data-testid="text-search-count">RESULTS FOR “{query}”{search.data ? ` · ${search.data.length}` : ''}</span></div><ProductCollection products={search.data} loading={search.isLoading} error={search.isError} retry={() => void search.refetch()} emptyTitle="No published products match that search."/></> : <div className="store-search-start"><span className="store-kicker">NOT SURE WHERE TO START?</span><h2>Browse by what you need.</h2><div><Link href="/ai-tools">AI tools <ArrowUpRight size={16}/></Link><Link href="/digital-products">Digital products <ArrowUpRight size={16}/></Link><Link href="/categories">All categories <ArrowUpRight size={16}/></Link></div></div>}</div></div>;
}
export function ProductPage() {
  const { slug = '' } = useParams<{ slug: string }>();
  const product = useProduct(slug);
  const data = product.data;
  const image = data?.imageUrl;
  return <div className="storefront"><div className="store-container store-product-page"><Link href="/shop" className="store-text-link">← Back to shop</Link>{product.isLoading ? <StateSkeleton/> : product.isError && statusOf(product.error) === 404 ? <StateEmpty title="This product isn't available." description="The listing may have moved or is not published. Browse the current collection instead."/> : product.isError ? <StateError retry={() => void product.refetch()}/> : !data?.slug || !data.name ? <StateEmpty title="This product isn't available." description="The listing may have moved or is not published. Browse the current collection instead."/> : <div className="store-detail"><div className="store-detail-image">{image ? <img src={image} alt={data.name}/> : <div className="store-product-art-fallback"><Layers3 size={54} strokeWidth={1.1}/><span>TUZAKAI / DIGITAL WORK</span></div>}</div><div className="store-detail-info"><span className="store-kicker">{data.categoryName || (data.productType === 'ai_tool' ? 'AI TOOL' : 'DIGITAL PRODUCT')}</span><h1>{data.name}</h1><p>{data.description || data.summary || 'Explore this resource from TuzakAI by Sztuzk.'}</p>{data.features.length > 0 && <ul className="store-detail-list">{data.features.map((feature, i) => <li key={i}>{feature}</li>)}</ul>}<div className="store-detail-rule"/><div className="store-detail-purchase"><h2>About availability</h2><p>Purchases are not available through this storefront yet. Product plans and payment readiness must be confirmed before checkout opens.</p><button type="button" className="store-button store-button-dark" disabled aria-disabled="true" data-testid="button-product-checkout">Checkout unavailable</button></div><Link href="/contact" className="store-text-link">Questions? Contact us <ArrowUpRight size={16}/></Link></div></div>}</div></div>;
}
export function CartPage() {
  return <div className="storefront"><PageIntro index="06" label="YOUR CART" title="The good stuff takes shape." description="Checkout is not available until product plans and payment setup are confirmed."/ ><div className="store-container store-section"><div className="store-cart-empty"><div className="store-cart-art"><ShoppingBag size={56} strokeWidth={1}/><span>NOTHING IN THE BAG</span></div><div><span className="store-kicker">YOUR CART / EMPTY</span><h2>No items here yet.</h2><p>Browse the collection and explore the tools. We won't take an order until checkout is properly ready.</p><Link href="/shop" className="store-button store-button-dark">Explore the shop <ArrowRight size={17}/></Link></div></div></div></div>;
}