/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface StoreCategory {
  id: string;
  name: string;
  slug: string;
  /** @nullable */
  description: string | null;
  active: boolean;
  createdAt: Date;
  updatedAt: Date;
}
