/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface StoreSupportTicketInput {
  /**
     * @minLength 1
     * @maxLength 160
     */
  name: string;
  /** @maxLength 254 */
  email: string;
  /**
     * @minLength 1
     * @maxLength 240
     */
  subject: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  message: string;
  /** @nullable */
  productId?: string | null;
}
