/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { StoreProductProductType } from './storeProductProductType';
import type { StoreProductStatus } from './storeProductStatus';

export interface StoreProduct {
  id: string;
  /** @nullable */
  categoryId: string | null;
  /** @nullable */
  categoryName: string | null;
  name: string;
  slug: string;
  productType: StoreProductProductType;
  /** @nullable */
  summary: string | null;
  /** @nullable */
  description: string | null;
  features: string[];
  requirements: string[];
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  whopProductId: string | null;
  /** @nullable */
  whopProductUrl: string | null;
  /** @nullable */
  deliveryUrl: string | null;
  /** @nullable */
  deliveryInstructions: string | null;
  status: StoreProductStatus;
  createdAt: Date;
  updatedAt: Date;
}
