/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type StoreProductStatus = typeof StoreProductStatus[keyof typeof StoreProductStatus];


export const StoreProductStatus = {
  draft: 'draft',
  published: 'published',
  archived: 'archived',
} as const;
