/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type StoreProductInputStatus = typeof StoreProductInputStatus[keyof typeof StoreProductInputStatus];


export const StoreProductInputStatus = {
  draft: 'draft',
  published: 'published',
  archived: 'archived',
} as const;
