/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type StoreProductProductType = typeof StoreProductProductType[keyof typeof StoreProductProductType];


export const StoreProductProductType = {
  digital: 'digital',
  ai_tool: 'ai_tool',
} as const;
