/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface TuzakaiSocialLinks {
  /** @nullable */
  instagram: string | null;
  /** @nullable */
  facebook: string | null;
  /** @nullable */
  pinterest: string | null;
  /** @nullable */
  youtube: string | null;
  /** @nullable */
  tiktok: string | null;
}
