import { useState, type ReactNode, type FormEvent } from 'react';
import { ArrowRight, ArrowUpRight, CircleHelp, Copy, Mail, Package, PenLine, Search, ShoppingBag, Sparkles, UserRound } from 'lucide-react';
import { useGetTuzakaiSiteSettings, useSubmitStoreSupportTicket } from '@workspace/api-client-react';
import { PageHeading, SiteLink as Link, ToolCard, toolLinks } from '../components/site';

const digital=['Jewelry Business Starter Kit','Jewelry Pricing Workbook','Jewelry Design Workbook','Jewelry Social Media Kit','Jewelry Packaging Templates','Jewelry Size Guide'];
const categories=[
  {title:'Jewelry design',description:'Go from a starting point to a considered concept.',path:'/tuzakai/'},
  {title:'Pricing & planning',description:'Put numbers and a plan behind your ideas.',path:'/jewelry-studio/pricing-calculator'},
  {title:'Business beginnings',description:'Find a practical first step for your creative venture.',path:'/jewelry-studio/start-business'},
  {title:'Listings & content',description:'Work on the words that help your work be seen.',path:'/jewelry-studio/etsy-listing'},
  {title:'Digital resources',description:'A growing library of guides and templates, coming soon.',path:'/digital-products'},
  {title:'Custom ideas',description:'Prepare a personal jewelry brief on this device.',path:'/custom-jewelry'}
];
function SectionHead({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle?:string}){return <div style={{marginBottom:35}}><div className="eyebrow">{eyebrow}</div><h2 className="section-title">{title}</h2>{subtitle&&<p className="muted" style={{lineHeight:1.7,maxWidth:650}}>{subtitle}</p>}</div>}
function SimplePage({kicker,title,description,children}:{kicker:string;title:string;description:string;children:ReactNode}){return <div className="container" style={{paddingBottom:100}}><PageHeading kicker={kicker} title={title} description={description}/>{children}</div>}
function ResourceCards(){return <div className="category-grid resource-grid">{digital.map((item,i)=><Link key={item} href="/digital-products" className="category-card" data-testid={`link-resource-${i}`}><span>{item}</span><span>COMING SOON <ArrowUpRight size={13} style={{display:'inline',verticalAlign:'middle'}}/></span></Link>)}</div>}

export function HomePage(){return <>
  <section className="hero"><div className="hero-copy"><div className="eyebrow">TUZAKAI BY SZTUZK · A CREATIVE WORKSPACE</div><h1>Ideas deserve<br/><em style={{fontWeight:400}}>room to grow.</em></h1><p>AI tools and digital products for creative entrepreneurs. Start with jewelry design, then explore the practical tools that help turn an idea into a direction.</p><div className="row" style={{marginTop:28}}><Link href="/tuzakai/" className="btn btn-dark" data-testid="link-hero-designer">Open Jewelry Designer <ArrowRight size={16}/></Link><Link href="/ai-tools" className="btn btn-outline" data-testid="link-hero-tools">Explore AI tools</Link></div><div className="hero-scroll"><span style={{width:25,height:1,background:'#a48562'}}/> CREATE · PLAN · EXPLORE</div></div><div className="hero-image" role="img" aria-label="Editorial jewelry image representing a starting point for creative ideas" style={{backgroundImage:"url('/jewelry-hero.png')"}}/></section>
  <section className="section"><div className="container split"><div><div className="eyebrow">01 / START HERE</div><h2 className="section-title" style={{fontSize:'clamp(40px,4.6vw,66px)'}}>From the first thought to something tangible.</h2><p className="muted" style={{lineHeight:1.9,maxWidth:480}}>TuzakAI begins with a jewelry designer made for exploration. Shape a concept, compare possibilities, and make decisions with more clarity. The wider workspace is built for creative entrepreneurs, not only jewelry makers.</p><Link href="/tuzakai/" className="link-arrow">Meet the Jewelry Designer <ArrowRight size={15}/></Link></div><div className="visual-block" role="img" aria-label="Editorial view of jewelry-making materials, not products for sale" style={{backgroundImage:"url('/jewelry-detail.png')"}}/></div></section>
  <section className="section editorial-band"><div className="container"><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:25,flexWrap:'wrap'}}><SectionHead eyebrow="02 / THE WORKSPACE" title="Tools for the making of it." subtitle="One main designer, plus the original Studio's focused planning tools. Explore what works for your next step."/><Link href="/ai-tools" className="link-arrow" style={{marginBottom:37}}>See all tools <ArrowRight size={15}/></Link></div><Link href="/tuzakai/" className="card" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:25,padding:'30px clamp(25px,4vw,54px)',marginBottom:18,flexWrap:'wrap'}} data-testid="link-featured-designer"><div><span className="eyebrow">FEATURED TOOL</span><h3 className="serif" style={{fontSize:'clamp(29px,3vw,42px)',margin:'10px 0'}}>TuzakAI Jewelry Designer <span style={{fontSize:17,color:'#8d765e'}}>by Sztuzk</span></h3><p className="muted" style={{margin:0}}>Explore jewelry concepts and thoughtful variations in the dedicated designer.</p></div><span className="btn btn-dark">Open designer <ArrowRight size={16}/></span></Link><div className="feature-grid">{toolLinks.map(item=><ToolCard key={item.path} item={item}/>)}</div><p className="fine" style={{marginTop:21}}>The five original Studio tools remain available at their existing links. Some use rule-based generation rather than AI.</p></div></section>
  <section className="section"><div className="container"><SectionHead eyebrow="03 / FIND YOUR DIRECTION" title="Follow the work, not a formula." subtitle="Whether you are sketching, costing, or writing, there is a place to begin."/><div className="category-grid">{categories.slice(0,4).map((item,i)=><Link key={item.title} href={item.path} className="category-card" data-testid={`link-home-category-${i}`}><span>{item.title}</span><span>EXPLORE <ArrowUpRight size={13} style={{display:'inline'}}/></span></Link>)}</div><Link href="/categories" className="link-arrow" style={{marginTop:27}}>Browse all categories <ArrowRight size={15}/></Link></div></section>
  <section className="section-sm editorial-band"><div className="container split"><div><div className="editorial-index">04.</div><SectionHead eyebrow="AN IDEA IN PROGRESS" title="Make space for the personal." subtitle="Have a jewelry idea that doesn't fit a template? Write your own brief, save it locally, and return to it later. This is a private planning draft, not an order or a sent request."/><Link href="/custom-jewelry" className="btn btn-dark">Prepare a custom brief <ArrowRight size={15}/></Link></div><div className="visual-block" role="img" aria-label="Editorial jewelry-making image; no item is offered for sale" style={{backgroundImage:"url('/jewelry-detail.png')",minHeight:490}}/></div></section>
  <section className="section"><div className="container"><SectionHead eyebrow="05 / ON THE HORIZON" title="Resources for the next chapter." subtitle="Six practical digital resources are in development. They are not available to purchase yet."/><ResourceCards/></div></section>
  <section className="section-sm editorial-band"><div className="container split"><div><SectionHead eyebrow="THE THINKING BEHIND IT" title="Creative work has more than one beginning." subtitle="TuzakAI by Sztuzk brings creative exploration and business-minded tools into one space. Jewelry is where the story starts, not where it has to end."/><Link href="/about" className="link-arrow">More about us <ArrowRight size={15}/></Link></div><div className="editorial-note"><PenLine size={28} strokeWidth={1.3} color="#9e7650"/><h3 className="serif" style={{fontSize:31,margin:'18px 0'}}>A better question can change the whole idea.</h3><p className="muted" style={{lineHeight:1.8}}>Explore freely. Check the details yourself. Keep what is useful and make the result your own.</p></div></div></section>
  <section className="section dark-band"><div className="container" style={{textAlign:'center'}}><div className="eyebrow" style={{color:'#c5a576'}}>YOUR NEXT STEP</div><h2 className="section-title" style={{fontSize:'clamp(40px,5vw,64px)',margin:'18px auto 28px',maxWidth:730}}>Start wherever the idea starts.</h2><div className="row" style={{justifyContent:'center'}}><Link href="/tuzakai/" className="btn btn-light">Open Jewelry Designer <ArrowRight size={16}/></Link><Link href="/digital-products" className="btn btn-gold">Explore digital resources</Link></div></div></section>
  </>}

export function AIToolsPage(){return <SimplePage kicker="THE TOOL LIBRARY" title="AI tools & creative utilities" description="Start with TuzakAI Jewelry Designer by Sztuzk, or visit the original Studio tools for focused creative and business planning."><Link href="/tuzakai/" className="card" style={{display:'block',padding:'clamp(28px,5vw,60px)',background:'#e8ddd0',marginBottom:28}} data-testid="link-ai-designer"><Sparkles size={27} strokeWidth={1.4} color="#986e43"/><div className="eyebrow" style={{marginTop:22}}>MAIN TOOL · TUZAKAI BY SZTUZK</div><h2 className="section-title" style={{marginTop:10}}>TuzakAI Jewelry Designer</h2><p className="muted" style={{lineHeight:1.8,maxWidth:670}}>A dedicated space to explore jewelry designs and variations. Use its suggestions as a creative starting point, then bring your own judgment to the details.</p><span className="link-arrow">Open designer <ArrowRight size={15}/></span></Link><SectionHead eyebrow="ORIGINAL STUDIO" title="Five more ways forward." subtitle="These legacy tools stay at their familiar URLs. Their generated outputs are drafts and estimates, not a substitute for your own review."/><div className="feature-grid">{toolLinks.map(item=><ToolCard key={item.path} item={item}/>)}</div><div className="notice" style={{marginTop:27}}>The original Studio's generators are rule-based. “AI Tools” refers to this broader workspace; not every tool uses AI.</div></SimplePage>}
export function DigitalPage(){return <SimplePage kicker="THE RESOURCE LIBRARY" title="Digital products" description="Practical resources for creative entrepreneurs, starting with jewelry makers. All six are coming soon."><div className="category-grid">{digital.map((item,i)=><div className="card" key={item} style={{padding:25,minHeight:210,display:'flex',flexDirection:'column',justifyContent:'space-between'}}><div className="tool-icon"><Package size={21}/></div><h2 className="serif" style={{fontSize:23,margin:'17px 0 auto'}}>{item}</h2><span className="eyebrow" style={{marginTop:20}}>COMING SOON · 0{i+1}</span></div>)}</div><div className="notice" style={{marginTop:30}}>These resources are not available for purchase yet. There is no active checkout for them.</div></SimplePage>}
export function CategoriesPage(){return <SimplePage kicker="EXPLORE BY NEED" title="Categories" description="Find a useful place to begin, from a first design to the business decisions around it."><div className="category-grid">{categories.map((item,i)=><Link href={item.path} className="category-card" style={{minHeight:205}} key={item.title} data-testid={`link-category-${i}`}><span>{item.title}</span><span className="fine" style={{letterSpacing:0,textTransform:'none'}}>{item.description}</span><span>EXPLORE <ArrowUpRight size={13} style={{display:'inline'}}/></span></Link>)}</div></SimplePage>}
export function ShopPage(){return <SimplePage kicker="EXPLORE THE WORKSPACE" title="Discover what's here" description="TuzakAI is a home for tools and developing digital resources, not a live jewelry store."><div className="split"><div className="visual-block" role="img" aria-label="Editorial jewelry photography, not a product listing" style={{backgroundImage:"url('/jewelry-hero.png')"}}/><div><h2 className="section-title">Ideas first. No storefront required.</h2><p className="muted" style={{lineHeight:1.8}}>The imagery here is editorial inspiration, not a catalog of products for sale. Explore the designer and resources within TuzakAI instead.</p><div className="row" style={{marginTop:25}}><Link href="/tuzakai/" className="btn btn-dark">Open Jewelry Designer <ArrowRight size={15}/></Link><Link href="/digital-products" className="btn btn-outline">Digital resources</Link></div></div></div></SimplePage>}
export function CustomPage(){const [form,setForm]=useState({style:'',type:'',details:'',budget:''});const [status,setStatus]=useState('');return <SimplePage kicker="A PERSONAL STARTING POINT" title="Prepare a custom brief" description="Give a jewelry idea a shape, in your own words. This is a private, in-browser draft."><div className="split" style={{alignItems:'start'}}><div><div className="visual-block" role="img" aria-label="Jewelry-making materials as editorial inspiration" style={{backgroundImage:"url('/jewelry-detail.png')"}}/><div className="notice" style={{marginTop:25}}>This form does not send a message, place an order, or create a commission. You can copy or save the draft on this device.</div><Link href="/tuzakai/" className="link-arrow" style={{marginTop:24}}>Explore in Jewelry Designer <ArrowRight size={15}/></Link></div><div className="card tool-panel"><h2 className="serif" style={{fontSize:30,marginTop:0}}>Your idea, your words.</h2><p className="muted">Avoid including sensitive personal information in your draft.</p><form className="stack" onSubmit={e=>{e.preventDefault();setStatus('Your brief is ready to copy or save. Nothing has been sent.')}}>{[['type','Jewelry type'],['style','Preferred style'],['budget','Approximate budget (optional)']].map(([key,label])=><label className="field" key={key}>{label}<input className="input" required={key!=='budget'} type="text" value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})} data-testid={`input-custom-${key}`}/></label>)}<label className="field">Your idea and requirements<textarea className="input" required value={form.details} onChange={e=>setForm({...form,details:e.target.value})} placeholder="Materials, colors, occasion, or anything else..." data-testid="input-custom-details"/></label><button className="btn btn-gold" type="submit" data-testid="button-prepare-brief">Prepare my brief <ArrowRight size={16}/></button></form>{status&&<div className="notice" role="status" style={{marginTop:20}} data-testid="status-custom-brief">{status}<div className="row" style={{marginTop:12}}><button className="btn btn-outline" onClick={()=>navigator.clipboard.writeText(JSON.stringify(form,null,2)).then(()=>setStatus('Brief copied. Nothing has been sent.')).catch(()=>setStatus('Copy unavailable in this browser. Nothing has been sent.'))} data-testid="button-copy-brief"><Copy size={14}/> Copy brief</button><button className="btn btn-outline" onClick={()=>{try{localStorage.setItem('sztuzk-custom-draft',JSON.stringify(form));setStatus('Saved on this device. Nothing has been sent.')}catch{setStatus('Unable to save this draft in your browser. Nothing has been sent.')}}} data-testid="button-save-brief">Save draft</button></div></div>}</div></div></SimplePage>}
export function AboutPage(){return <SimplePage kicker="OUR STORY" title="About TuzakAI by Sztuzk" description="A creative marketplace for the people building something of their own."><div className="split"><div><h2 className="section-title">It begins with an idea.</h2><p className="muted" style={{fontSize:17,lineHeight:1.9}}>TuzakAI by Sztuzk brings AI tools and digital products together for creative entrepreneurs. Jewelry is our starting point: a tangible way to explore form, materials, pricing, and the decisions behind a creative business.</p><p className="muted" style={{lineHeight:1.8}}>The dedicated TuzakAI Jewelry Designer is the first featured tool. The original Studio remains available for practical tasks such as pricing, business planning, and listing drafts. Published digital products appear in the shop as the collection grows.</p><p className="muted" style={{lineHeight:1.8}}>Explore the tools, browse the collection, and keep moving from first thought to next step. What begins with jewelry can grow into more.</p><Link href="/shop" className="btn btn-gold">Explore the shop <ArrowRight size={16}/></Link></div><div className="visual-block" role="img" aria-label="Editorial image illustrating the creative process" style={{backgroundImage:"url('/creative-detail.png')",minHeight:520}}/></div></SimplePage>}
export function ContactPage(){
  const {data:settings}=useGetTuzakaiSiteSettings();
  const submitTicket=useSubmitStoreSupportTicket();
  const [form,setForm]=useState({name:'',email:'',subject:'',message:''});
  const [error,setError]=useState('');
  const [reference,setReference]=useState('');
  const email=settings?.supportEmail?.trim()&&!settings.supportEmail.toLowerCase().endsWith('jewelry.com')?settings.supportEmail.trim():null;
  const submit=async(e:FormEvent<HTMLFormElement>)=>{
    e.preventDefault();setError('');setReference('');
    const data={name:form.name.trim(),email:form.email.trim(),subject:form.subject.trim(),message:form.message.trim()};
    if(!data.name||!data.email||!data.subject||!data.message){setError('Complete all fields before sending.');return;}
    if(data.name.length>160||data.email.length>254||data.subject.length>240||data.message.length>10000){setError('One or more fields exceed the allowed length.');return;}
    try{
      const ticket=await submitTicket.mutateAsync({data});
      if(!ticket.id)throw new Error('The submission could not be confirmed. Please try again.');
      setReference(ticket.id);setForm({name:'',email:'',subject:'',message:''});
    }catch(err){setError(err instanceof Error?err.message:'Could not submit your request. Please try again.');}
  };
  return <SimplePage kicker="HERE TO HELP" title="Contact / Support" description="Questions about a tool or the collection? Send us a support request."><div className="split" style={{alignItems:'start'}}><div><h2 className="section-title">Let's find the next step.</h2><p className="muted" style={{lineHeight:1.8}}>For quick answers, start with the FAQ. Work saved in the legacy Studio remains in this browser; export anything important before clearing site data.</p><Link href="/faq" className="btn btn-dark" style={{marginTop:18}}>Read the FAQ <ArrowRight size={15}/></Link>{email&&<div className="quiet-panel" style={{marginTop:30}}><Mail size={20} color="#a78555"/><h3 className="serif" style={{fontSize:24,margin:'12px 0 7px'}}>Prefer email?</h3><a href={`mailto:${email}`} className="link-arrow" data-testid="link-support-email">{email} <ArrowRight size={15}/></a></div>}</div><div className="card tool-panel"><h2 className="serif" style={{fontSize:28,marginTop:0}}>Send a support request</h2><p className="muted">Your message will be saved for review. Do not include passwords, payment details, or sensitive information.</p><form className="stack" onSubmit={e=>void submit(e)}><div className="form-grid"><label className="field">Name<input required maxLength={160} className="input" autoComplete="name" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} data-testid="input-support-name"/></label><label className="field">Email<input required maxLength={254} type="email" className="input" autoComplete="email" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))} data-testid="input-support-email"/></label></div><label className="field">Subject<input required maxLength={240} className="input" value={form.subject} onChange={e=>setForm(f=>({...f,subject:e.target.value}))} data-testid="input-support-subject"/></label><label className="field">Message<textarea required maxLength={10000} className="input" value={form.message} onChange={e=>setForm(f=>({...f,message:e.target.value}))} data-testid="input-support-message"/></label><button className="btn btn-gold" type="submit" disabled={submitTicket.isPending} data-testid="button-submit-support">{submitTicket.isPending?'Sending request…':'Send request'} <ArrowRight size={15}/></button></form>{error&&<div className="notice" role="alert" style={{marginTop:20,borderLeftColor:'#9D3D37'}} data-testid="status-support-error">{error}</div>}{reference&&<div className="notice" role="status" style={{marginTop:20}} data-testid="status-support-success">Request received and saved for review. Reference: {reference}. This form does not send an email confirmation.</div>}</div></div></SimplePage>;
}
export function SearchPage(){const [query,setQuery]=useState('');const options=[{title:'TuzakAI Jewelry Designer',description:'The main creative design tool.',path:'/tuzakai/',group:'AI tool'},...toolLinks.map(item=>({title:item.title,description:item.desc,path:item.path,group:'Original Studio'})),...digital.map(title=>({title,description:'Digital resource coming soon.',path:'/digital-products',group:'Coming soon'})),...categories.map(item=>({title:item.title,description:item.description,path:item.path,group:'Category'}))];const results=options.filter(item=>(item.title+' '+item.description+' '+item.group).toLowerCase().includes(query.trim().toLowerCase()));return <SimplePage kicker="FIND YOUR WAY" title="Search" description="Search available tools, categories, and upcoming resources."><label className="search-input-wrap"><Search size={20} color="#8d765e"/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try design, pricing, or business..." aria-label="Search tools and resources" data-testid="input-site-search"/></label><p className="fine" role="status" data-testid="text-search-count">{results.length} {results.length===1?'result':'results'}{query.trim()?` for “${query.trim()}”`:''}</p>{results.length?<div className="search-results">{results.map((item,i)=><Link key={`${item.path}-${item.title}`} href={item.path} className="card" data-testid={`link-search-result-${i}`}><span className="eyebrow">{item.group}</span><h2>{item.title}</h2><p className="muted" style={{fontSize:13,lineHeight:1.7}}>{item.description}</p><span className="link-arrow">Explore <ArrowRight size={14}/></span></Link>)}</div>:<div className="quiet-panel" style={{marginTop:28}}><h2 className="serif" style={{fontSize:27,margin:'0 0 8px'}}>Nothing matched that phrase.</h2><p className="muted">Try a broader word, or explore all categories.</p><Link href="/categories" className="link-arrow">Browse categories <ArrowRight size={14}/></Link></div>}</SimplePage>}
export function CartPage(){return <SimplePage kicker="YOUR CART" title="Nothing to check out yet." description="The digital resource library is still in development, so purchases and checkout are not available."><div className="quiet-panel" style={{maxWidth:680,textAlign:'center',margin:'0 auto',padding:'55px 35px'}}><ShoppingBag size={30} strokeWidth={1.2} color="#9e7650" style={{margin:'auto'}}/><h2 className="section-title">Your cart is empty.</h2><p className="muted" style={{lineHeight:1.8}}>The six digital resources are coming soon. In the meantime, explore the tools that are available now.</p><div className="row" style={{justifyContent:'center',marginTop:27}}><Link href="/ai-tools" className="btn btn-dark">Explore tools <ArrowRight size={15}/></Link><Link href="/digital-products" className="btn btn-outline">View upcoming resources</Link></div></div></SimplePage>}
export function SignInPage(){return <SimplePage kicker="ACCOUNT" title="A workspace in progress." description="Account sign-in is not available on this site yet. There is no account you need to create to explore the current tools."><div className="quiet-panel" style={{maxWidth:680,margin:'0 auto',textAlign:'center',padding:'55px 35px'}}><UserRound size={30} strokeWidth={1.2} color="#9e7650" style={{margin:'auto'}}/><h2 className="section-title">No sign-in needed to start.</h2><p className="muted" style={{lineHeight:1.8}}>The original Studio saves projects on this device. Export important work before clearing your browser data. Account features may be added later.</p><Link href="/ai-tools" className="btn btn-dark" style={{marginTop:20}}>Explore tools <ArrowRight size={15}/></Link></div></SimplePage>}
const questions=[
  ['Do I need an account to use the tools?','No. The five original Studio tools work without an account and save projects in this browser. Export important work before clearing browser data.'],
  ['Which tool uses AI?','TuzakAI Jewelry Designer is the main AI tool. The original Studio generators use deterministic rule-based generation; review all outputs yourself.'],
  ['Are material costs and selling prices exact?','No. The legacy pricing calculator uses the numbers you enter and returns estimates. Check actual supplier costs and fees before making a business decision.'],
  ['Can I move an idea between original Studio tools?','Yes. The original Studio lets you take an idea into design, pricing, and an Etsy listing draft. Shared context is stored locally on this device.'],
  ['Can I publish an Etsy listing directly?','No. The tool prepares a draft. Verify the details and current Etsy rules yourself before publishing.'],
  ['Can I buy a digital product yet?','Checkout is not available until product plans and payment setup are confirmed. Browse published listings for current details.'],
  ['Can I send a custom jewelry request?','No. The custom brief is a local planning draft and does not send a message or place an order.'],
  ['Is there a jewelry store here?','TuzakAI is a marketplace for AI tools and digital resources for creative entrepreneurs, not a physical jewelry store.']
];
export function FAQPage(){return <SimplePage kicker="GOOD TO KNOW" title="Frequently asked questions" description="A few honest answers before you begin."><div style={{maxWidth:850}}>{questions.map(([q,a])=><details className="card" key={q} style={{marginBottom:12,padding:'0 25px'}}><summary style={{cursor:'pointer',padding:'21px 0',fontFamily:'Playfair Display,serif',fontSize:20,listStyle:'none',display:'flex',justifyContent:'space-between',gap:20}}>{q}<CircleHelp size={18} color="#aa8958" style={{flexShrink:0}}/></summary><p className="muted" style={{lineHeight:1.8,borderTop:'1px solid #e9dfd2',paddingTop:16,margin:'0 0 22px'}}>{a}</p></details>)}</div></SimplePage>}
export function NotFoundPage(){return <div className="container" style={{padding:'110px 0 150px',textAlign:'center'}}><div className="eyebrow">PAGE NOT FOUND</div><h1 className="serif" style={{fontSize:65}}>A little off the path.</h1><p className="muted">This page isn't here. Let's get you back to making.</p><Link href="/" className="btn btn-gold" style={{marginTop:25}}>Back to home <ArrowRight size={16}/></Link></div>}